-- Excel DB Import: airline_operations upsert
-- Generated from 278 records

UPDATE airline_operations SET firms_code = 'F670', isc_amount = 180.5 WHERE id = 1;
UPDATE airline_operations SET isc_amount = 100 WHERE id = 2;
UPDATE airline_operations SET isc_amount = 95 WHERE id = 4;
UPDATE airline_operations SET isc_amount = 75 WHERE id = 5;
UPDATE airline_operations SET isc_amount = 75 WHERE id = 6;
UPDATE airline_operations SET isc_amount = 90 WHERE id = 28;
UPDATE airline_operations SET firms_code = 'V182' WHERE id = 351;
UPDATE airline_operations SET isc_amount = 170 WHERE id = 9;
UPDATE airline_operations SET isc_amount = 210 WHERE id = 33;
UPDATE airline_operations SET isc_amount = 90 WHERE id = 11;
UPDATE airline_operations SET firms_code = 'W934', isc_amount = 165 WHERE id = 35;
UPDATE airline_operations SET firms_code = 'SAX6', isc_amount = 150 WHERE id = 345;
UPDATE airline_operations SET isc_amount = 175 WHERE id = 37;
UPDATE airline_operations SET isc_amount = 80 WHERE id = 38;
UPDATE airline_operations SET isc_amount = 160 WHERE id = 12;
UPDATE airline_operations SET isc_amount = 85 WHERE id = 39;
UPDATE airline_operations SET firms_code = 'E435' WHERE id = 40;
UPDATE airline_operations SET firms_code = 'M652', isc_amount = 65 WHERE id = 58;
UPDATE airline_operations SET contact_email = 'JFK66AMS@WFS.AERO; jfk66leads@wfs.aero; infoamerica@wfs.aero', isc_amount = 210.5 WHERE id = 13;
UPDATE airline_operations SET isc_amount = 160 WHERE id = 14;
UPDATE airline_operations SET isc_amount = 145, isc_payable_at = 'Air General MCO' WHERE id = 44;
UPDATE airline_operations SET isc_amount = 130 WHERE id = 46;
UPDATE airline_operations SET isc_amount = 215 WHERE id = 47;
UPDATE airline_operations SET firms_code = 'J628, I866', isc_amount = 115 WHERE id = 48;
UPDATE airline_operations SET firms_code = 'N192', isc_amount = 120 WHERE id = 50;
UPDATE airline_operations SET firms_code = 'O708', isc_amount = 60 WHERE id = 55;
UPDATE airline_operations SET isc_amount = 160 WHERE id = 56;
UPDATE airline_operations SET isc_amount = 200 WHERE id = 57;
UPDATE airline_operations SET isc_amount = 55 WHERE id = 59;
UPDATE airline_operations SET isc_amount = 80 WHERE id = 61;
UPDATE airline_operations SET isc_amount = 205 WHERE id = 62;
UPDATE airline_operations SET firms_code = 'W005', isc_amount = 150 WHERE id = 63;
UPDATE airline_operations SET isc_amount = 105 WHERE id = 66;
UPDATE airline_operations SET isc_amount = 95 WHERE id = 67;
UPDATE airline_operations SET isc_amount = 95 WHERE id = 68;
UPDATE airline_operations SET isc_amount = 90 WHERE id = 70;
UPDATE airline_operations SET firms_code = 'L320', isc_amount = 70 WHERE id = 71;
UPDATE airline_operations SET isc_amount = 90 WHERE id = 72;
UPDATE airline_operations SET firms_code = 'S984', isc_amount = 90 WHERE id = 75;
UPDATE airline_operations SET firms_code = 'K740', isc_amount = 60 WHERE id = 77;
UPDATE airline_operations SET isc_amount = 80 WHERE id = 78;
UPDATE airline_operations SET isc_amount = 80 WHERE id = 79;
UPDATE airline_operations SET firms_code = 'W865', isc_amount = 80 WHERE id = 80;
UPDATE airline_operations SET isc_amount = 80 WHERE id = 81;
UPDATE airline_operations SET isc_amount = 80 WHERE id = 82;
UPDATE airline_operations SET isc_amount = 80 WHERE id = 83;
UPDATE airline_operations SET isc_amount = 95 WHERE id = 84;
UPDATE airline_operations SET isc_amount = 95 WHERE id = 85;
UPDATE airline_operations SET isc_amount = 90 WHERE id = 89;
UPDATE airline_operations SET isc_amount = 230 WHERE id = 16;
UPDATE airline_operations SET firms_code = 'N421', isc_amount = 65 WHERE id = 90;
UPDATE airline_operations SET firms_code = 'WAX4', isc_amount = 220 WHERE id = 91;
UPDATE airline_operations SET isc_amount = 75 WHERE id = 92;
UPDATE airline_operations SET isc_amount = 100 WHERE id = 93;
UPDATE airline_operations SET firms_code = 'E078' WHERE id = 94;
UPDATE airline_operations SET firms_code = 'A308' WHERE id = 95;
UPDATE airline_operations SET isc_payable_at = 'PAYCARGO / CARGOSPRINT', firms_code = 'SCO8', isc_amount = 120 WHERE id = 17;
UPDATE airline_operations SET firms_code = 'A156', isc_amount = 205 WHERE id = 96;
UPDATE airline_operations SET isc_amount = 185 WHERE id = 98;
UPDATE airline_operations SET isc_amount = 80 WHERE id = 99;
UPDATE airline_operations SET isc_amount = 200 WHERE id = 100;
UPDATE airline_operations SET firms_code = 'E435' WHERE id = 101;
UPDATE airline_operations SET isc_amount = 50 WHERE id = 102;
UPDATE airline_operations SET isc_amount = 160 WHERE id = 104;
UPDATE airline_operations SET isc_amount = 175 WHERE id = 108;
UPDATE airline_operations SET isc_amount = 100 WHERE id = 109;
UPDATE airline_operations SET contact_number = '718-928-2900 / 718-880-3503', firms_code = 'E208' WHERE id = 112;
UPDATE airline_operations SET isc_amount = 110 WHERE id = 113;
INSERT INTO airline_operations (airline_id, airport_id, contact_email) VALUES (221, 54, 'AIRMEM <AIRMEM@acceleratedusa.com>') ON CONFLICT DO NOTHING;
UPDATE airline_operations SET isc_amount = 100 WHERE id = 114;
UPDATE airline_operations SET isc_amount = 140 WHERE id = 116;
UPDATE airline_operations SET isc_amount = 100 WHERE id = 117;
UPDATE airline_operations SET isc_amount = 100 WHERE id = 118;
UPDATE airline_operations SET isc_amount = 50 WHERE id = 119;
INSERT INTO airline_operations (airline_id, airport_id, firms_code, isc_amount, contact_number, contact_email) VALUES (1, 4, 'T275', 50, '800-227-4622*3', 'Khalifa, Fatima <Fatima.Khalifa@aa.com>; DFWCARGO, Gateway Service Recovery <DFWCargo.Customerservice@aa.com>; airportinfocenter@dfwairport.com; AMS, DFWCargo <DFWCargo.AMS@aa.com>; Vandiver, Kathleen <Kathleen.Vandiver@aa.com>; King, Corby <Corby.King@aa.com>; Abdelrahman, Tanzeel <Tanzeel.Abdelrahman@aa.com>; Simon, Trevon <Trevon.Simon@aa.com>') ON CONFLICT DO NOTHING;
UPDATE airline_operations SET isc_amount = 100 WHERE id = 121;
UPDATE airline_operations SET isc_amount = 140 WHERE id = 24;
INSERT INTO airline_operations (airline_id, airport_id, firms_code, contact_number) VALUES (238, 12, 'S987/S991', '281-214-2260') ON CONFLICT DO NOTHING;
UPDATE airline_operations SET isc_amount = 160 WHERE id = 126;
UPDATE airline_operations SET isc_amount = 100 WHERE id = 127;
UPDATE airline_operations SET isc_amount = 80 WHERE id = 128;
UPDATE airline_operations SET firms_code = 'M503/O967', isc_payable_to = 'ALLIANCE GROUND', contact_number = '305-492-8620 / (305) 397-0161 X3', contact_email = 'aaraujo@agi.aero; yperera@agi.aero; miaoffice@allianceground.com' WHERE id = 135;
UPDATE airline_operations SET firms_code = 'E437' WHERE id = 136;
UPDATE airline_operations SET isc_amount = 80 WHERE id = 141;
UPDATE airline_operations SET isc_amount = 150 WHERE id = 142;
UPDATE airline_operations SET isc_amount = 225 WHERE id = 144;
UPDATE airline_operations SET contact_email = 'jfkimport@dlh.de', isc_amount = 119 WHERE id = 145;
UPDATE airline_operations SET isc_payable_to = 'wfs', contact_number = 'Linda  847-737-2329', contact_email = 'ordk4import@wfs.aero.com' WHERE id = 150;
UPDATE airline_operations SET firms_code = 'E437 (CHOICE AVIATION SERVICES)' WHERE id = 154;
UPDATE airline_operations SET isc_amount = 100 WHERE id = 21;
UPDATE airline_operations SET isc_amount = 129 WHERE id = 156;
UPDATE airline_operations SET firms_code = 'I803', isc_amount = 95 WHERE id = 157;
UPDATE airline_operations SET isc_amount = 120 WHERE id = 158;
UPDATE airline_operations SET isc_amount = 100 WHERE id = 162;
UPDATE airline_operations SET isc_amount = 60 WHERE id = 163;
UPDATE airline_operations SET firms_code = 'SAX7', isc_amount = 200 WHERE id = 165;
UPDATE airline_operations SET isc_payable_at = 'laxops <laxops@wfs.aero>' WHERE id = 166;
UPDATE airline_operations SET isc_amount = 170 WHERE id = 172;
INSERT INTO airline_operations (airline_id, airport_id, firms_code) VALUES (59, 28, 'V244') ON CONFLICT DO NOTHING;
UPDATE airline_operations SET contact_email = 'FORWARD AIR CHICAGO 847-297-5730' WHERE id = 174;
UPDATE airline_operations SET contact_email = 'PHL_IMPORTS@FORWARDAIR.COM', isc_amount = 80 WHERE id = 180;
UPDATE airline_operations SET firms_code = 'A308' WHERE id = 185;
UPDATE airline_operations SET isc_amount = 100 WHERE id = 187;
UPDATE airline_operations SET firms_code = 'M503', isc_amount = 145 WHERE id = 188;
UPDATE airline_operations SET isc_amount = 170 WHERE id = 189;
UPDATE airline_operations SET firms_code = 'M503' WHERE id = 190;
UPDATE airline_operations SET contact_number = '786-507-0462' WHERE id = 192;
UPDATE airline_operations SET firms_code = 'Y732' WHERE id = 193;
UPDATE airline_operations SET isc_amount = 175 WHERE id = 194;
UPDATE airline_operations SET isc_amount = 150 WHERE id = 195;
INSERT INTO airline_operations (airline_id, airport_id, firms_code) VALUES (20, 1486, 'Q710') ON CONFLICT DO NOTHING;
UPDATE airline_operations SET isc_amount = 80 WHERE id = 204;
UPDATE airline_operations SET firms_code = 'O419' WHERE id = 205;
UPDATE airline_operations SET firms_code = 'N664' WHERE id = 209;
UPDATE airline_operations SET firms_code = 'E437' WHERE id = 210;
UPDATE airline_operations SET firms_code = 'E437' WHERE id = 212;
UPDATE airline_operations SET isc_amount = 90 WHERE id = 213;
UPDATE airline_operations SET isc_payable_to = 'wfs', contact_email = 'cargolax@swiss.com, lxops@wfs.aero' WHERE id = 214;
UPDATE airline_operations SET firms_code = 'E827', isc_amount = 205, isc_payable_to = 'wfs/swissport', contact_number = '718-215-2004', contact_email = 'mtalukder@wfs.aero , cargojfk@swiss.com' WHERE id = 215;
INSERT INTO airline_operations (airline_id, airport_id, firms_code, contact_number) VALUES (41, 11, 'M503', '305-492-8620') ON CONFLICT DO NOTHING;
UPDATE airline_operations SET firms_code = 'E964/E045/EAC9' WHERE id = 371;
UPDATE airline_operations SET firms_code = 'J766' WHERE id = 222;
INSERT INTO airline_operations (airline_id, airport_id, firms_code, contact_number) VALUES (75, 11, 'M652', '305 874 2700') ON CONFLICT DO NOTHING;
UPDATE airline_operations SET contact_email = 'jfkffrj@rj.com; Hmoud.Manasir@rj.com; Daniel.Durso@rj.com; VDaniel@allianceground.com; RJJFKStaff@allianceground.com; MABrown@allianceground.com' WHERE id = 225;
INSERT INTO airline_operations (airline_id, airport_id, firms_code, isc_payable_to, contact_number, contact_email) VALUES (45, 3, 'H123', 'ALLIANCE GROUND', '773-686-5840 / 773-683-3940 EXT 7 / 212-949-0060 ex 4172', 'ORDRJOPS@allianceground.com') ON CONFLICT DO NOTHING;
INSERT INTO airline_operations (airline_id, airport_id, firms_code, isc_payable_to, contact_number, contact_email) VALUES (45, 10, 'M836', 'FORWARDAIR', '407-857-9212', '_fa_mco@forwardair.com') ON CONFLICT DO NOTHING;
UPDATE airline_operations SET firms_code = 'E437' WHERE id = 226;
INSERT INTO airline_operations (airline_id, airport_id, firms_code, isc_payable_to, contact_number, contact_email) VALUES (85, 22, 'V079', 'FORWARDAIR', '800-726-6654', 'Customer Care <custserv@forwardair.com>') ON CONFLICT DO NOTHING;
UPDATE airline_operations SET isc_amount = 120 WHERE id = 137;
UPDATE airline_operations SET contact_email = 'b151cl@wfs.aero', isc_amount = 130 WHERE id = 228;
UPDATE airline_operations SET firms_code = 'E437' WHERE id = 229;
INSERT INTO airline_operations (airline_id, airport_id, firms_code, isc_amount, contact_number, contact_email) VALUES (14, 1250, 'I124', 100, '734-710-0373', 'sking@cfsdtw.com') ON CONFLICT DO NOTHING;
UPDATE airline_operations SET firms_code = 'K542', isc_amount = 80 WHERE id = 232;
INSERT INTO airline_operations (airline_id, airport_id, firms_code, contact_number) VALUES (14, 25, 'Q088', '(615) 367-0949') ON CONFLICT DO NOTHING;
UPDATE airline_operations SET isc_amount = 100 WHERE id = 26;
UPDATE airline_operations SET firms_code = 'M371', isc_amount = 100 WHERE id = 235;
UPDATE airline_operations SET firms_code = 'E437' WHERE id = 238;
INSERT INTO airline_operations (airline_id, airport_id, firms_code, contact_number, contact_email) VALUES (60, 1, 'L804', '404-684-6805 / 404-766-7762', 'atl@specialservice.net') ON CONFLICT DO NOTHING;
UPDATE airline_operations SET isc_amount = 165 WHERE id = 240;
UPDATE airline_operations SET isc_payable_at = 'EPIC', contact_number = '718-880-3422', firms_code = 'F259', isc_amount = 110 WHERE id = 25;
UPDATE airline_operations SET firms_code = 'E437' WHERE id = 241;
UPDATE airline_operations SET firms_code = 'F149' WHERE id = 244;
UPDATE airline_operations SET isc_amount = 90 WHERE id = 246;
UPDATE airline_operations SET isc_amount = 100 WHERE id = 247;
UPDATE airline_operations SET firms_code = 'E006' WHERE id = 249;
UPDATE airline_operations SET isc_amount = 110 WHERE id = 251;
UPDATE airline_operations SET firms_code = 'SAX6' WHERE id = 252;
UPDATE airline_operations SET firms_code = 'O754' WHERE id = 253;
INSERT INTO airline_operations (airline_id, airport_id, contact_number) VALUES (239, 12, '800-722-0081') ON CONFLICT DO NOTHING;
UPDATE airline_operations SET firms_code = 'E851' WHERE id = 259;
UPDATE airline_operations SET firms_code = 'MERCURY AIR CARGO (Y270)' WHERE id = 260;
INSERT INTO airline_operations (airline_id, airport_id, firms_code, isc_amount, contact_number, contact_email) VALUES (52, 1, 'M933', 120, 'CHICAGO
 630-616-8925', 'ATLCSR@ACCELERATEDUSA.COM') ON CONFLICT DO NOTHING;
INSERT INTO airline_operations (airline_id, airport_id, firms_code) VALUES (52, 28, 'V244') ON CONFLICT DO NOTHING;
INSERT INTO airline_operations (airline_id, airport_id, firms_code, isc_amount, isc_payable_to, contact_email) VALUES (52, 13, 'A308', 195, 'swissport', 'EX-STCARGO-BOS-HU@SWISSPORT.COM//EX-SPCARGO-BOS-HU@swissport.com') ON CONFLICT DO NOTHING;
INSERT INTO airline_operations (airline_id, airport_id, firms_code, contact_number, contact_email) VALUES (52, 20, 'O708', '704-357-0990', 'CLTIMPORT@ACCELERATEDUSA.COM') ON CONFLICT DO NOTHING;
INSERT INTO airline_operations (airline_id, airport_id, firms_code, isc_amount, isc_payable_to, contact_number, contact_email) VALUES (52, 7, 'W698', 160, 'Alliance GROUND', '650-821-0855', 'SFOAGI@ALLIANCEGROUND.COM') ON CONFLICT DO NOTHING;
UPDATE airline_operations SET isc_amount = 125 WHERE id = 262;
UPDATE airline_operations SET isc_amount = 200 WHERE id = 266;
UPDATE airline_operations SET firms_code = 'M735' WHERE id = 267;
INSERT INTO airline_operations (airline_id, airport_id, firms_code, isc_amount) VALUES (2, 20, 'L323', 100) ON CONFLICT DO NOTHING;
INSERT INTO airline_operations (airline_id, airport_id, firms_code, isc_amount) VALUES (2, 4, 'T282', 100) ON CONFLICT DO NOTHING;
INSERT INTO airline_operations (airline_id, airport_id, firms_code, isc_amount) VALUES (2, 54, 'P490', 100) ON CONFLICT DO NOTHING;
INSERT INTO airline_operations (airline_id, airport_id, isc_amount, isc_payable_to, contact_email) VALUES (2, 2, 140, 'delta', 'DLCARGO@delta.com') ON CONFLICT DO NOTHING;
INSERT INTO airline_operations (airline_id, airport_id, firms_code) VALUES (2, 41, 'HAH5') ON CONFLICT DO NOTHING;
INSERT INTO airline_operations (airline_id, airport_id, firms_code, isc_amount, isc_payable_to, contact_number, contact_email) VALUES (2, 6, 'E781', 140, 'delta', '800 352 2746', 'Dlcargo@delta.com') ON CONFLICT DO NOTHING;
UPDATE airline_operations SET firms_code = 'L720' WHERE id = 270;
INSERT INTO airline_operations (airline_id, airport_id, isc_amount, isc_payable_to, contact_email) VALUES (70, 7, 175, 'swissport', 'Pillay, Anuman'' <anuman.pillay@swissport.com>; ''APM SFO'' <apm.sfo@airindia.com>; ''Lumibao, Magida'' <Magida.Lumibao@swissport.com>; ''Zuniga, Maria'' <Maria.Zuniga@swissport.com>; ''sfotkcargo@swissport.com''') ON CONFLICT DO NOTHING;
INSERT INTO airline_operations (airline_id, airport_id, isc_payable_to, contact_number, contact_email) VALUES (70, 6, 'wfs', '718-880-3461', 'Dylan Singh (dsingh@wfs.aero, ).') ON CONFLICT DO NOTHING;
INSERT INTO airline_operations (airline_id, airport_id, firms_code, isc_amount, contact_number, contact_email) VALUES (70, 1, 'M641', 75, '(800) 535-2345 / 404.346.9777 x29111', 'mhothi@ups.com , upsairatl@stgusa.com, nikki.sanders@stgusa.com') ON CONFLICT DO NOTHING;
INSERT INTO airline_operations (airline_id, airport_id, firms_code, contact_number, contact_email) VALUES (241, 6, 'EAO7', '718-244-7777', 'freighterops@msnairservice.com') ON CONFLICT DO NOTHING;