-- ISC Charges update from USA_100_Airports_Cargo_Handlers Excel
-- Generated: 2026-03-25T09:02:57.183Z
-- 534 update statements

UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 39 AND airport_id = 6;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 40 AND airport_id = 6;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 24 AND airport_id = 6;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 25 AND airport_id = 6;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 226 AND airport_id = 6;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 38 AND airport_id = 6;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 39 AND airport_id = 2;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 40 AND airport_id = 2;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 24 AND airport_id = 2;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 25 AND airport_id = 2;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 226 AND airport_id = 2;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 38 AND airport_id = 2;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 39 AND airport_id = 3;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 40 AND airport_id = 3;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 24 AND airport_id = 3;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 25 AND airport_id = 3;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 226 AND airport_id = 3;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 38 AND airport_id = 3;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 39 AND airport_id = 4;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 40 AND airport_id = 4;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 24 AND airport_id = 4;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 25 AND airport_id = 4;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 226 AND airport_id = 4;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 38 AND airport_id = 4;
UPDATE airline_operations SET isc_amount = '90-180', isc_payable_to = 'AGI', last_updated = NOW() WHERE airline_id = 39 AND airport_id = 11;
UPDATE airline_operations SET isc_amount = '90-180', isc_payable_to = 'AGI', last_updated = NOW() WHERE airline_id = 40 AND airport_id = 11;
UPDATE airline_operations SET isc_amount = '90-180', isc_payable_to = 'AGI', last_updated = NOW() WHERE airline_id = 24 AND airport_id = 11;
UPDATE airline_operations SET isc_amount = '90-180', isc_payable_to = 'AGI', last_updated = NOW() WHERE airline_id = 25 AND airport_id = 11;
UPDATE airline_operations SET isc_amount = '90-180', isc_payable_to = 'AGI', last_updated = NOW() WHERE airline_id = 226 AND airport_id = 11;
UPDATE airline_operations SET isc_amount = '90-180', isc_payable_to = 'AGI', last_updated = NOW() WHERE airline_id = 38 AND airport_id = 11;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 39 AND airport_id = 1;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 40 AND airport_id = 1;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 24 AND airport_id = 1;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 25 AND airport_id = 1;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 226 AND airport_id = 1;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 38 AND airport_id = 1;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 39 AND airport_id = 7;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 40 AND airport_id = 7;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 24 AND airport_id = 7;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 25 AND airport_id = 7;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 226 AND airport_id = 7;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 38 AND airport_id = 7;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 39 AND airport_id = 12;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 40 AND airport_id = 12;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 24 AND airport_id = 12;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 25 AND airport_id = 12;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 226 AND airport_id = 12;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 38 AND airport_id = 12;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 39 AND airport_id = 8;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 40 AND airport_id = 8;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 24 AND airport_id = 8;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 25 AND airport_id = 8;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 226 AND airport_id = 8;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 38 AND airport_id = 8;
UPDATE airline_operations SET isc_amount = '90-180', isc_payable_to = 'AGI', last_updated = NOW() WHERE airline_id = 39 AND airport_id = 13;
UPDATE airline_operations SET isc_amount = '90-180', isc_payable_to = 'AGI', last_updated = NOW() WHERE airline_id = 40 AND airport_id = 13;
UPDATE airline_operations SET isc_amount = '90-180', isc_payable_to = 'AGI', last_updated = NOW() WHERE airline_id = 24 AND airport_id = 13;
UPDATE airline_operations SET isc_amount = '90-180', isc_payable_to = 'AGI', last_updated = NOW() WHERE airline_id = 25 AND airport_id = 13;
UPDATE airline_operations SET isc_amount = '90-180', isc_payable_to = 'AGI', last_updated = NOW() WHERE airline_id = 226 AND airport_id = 13;
UPDATE airline_operations SET isc_amount = '90-180', isc_payable_to = 'AGI', last_updated = NOW() WHERE airline_id = 38 AND airport_id = 13;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 39 AND airport_id = 126;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 40 AND airport_id = 126;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 24 AND airport_id = 126;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 25 AND airport_id = 126;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 226 AND airport_id = 126;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 38 AND airport_id = 126;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 39 AND airport_id = 16;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 40 AND airport_id = 16;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 24 AND airport_id = 16;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 25 AND airport_id = 16;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 226 AND airport_id = 16;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 38 AND airport_id = 16;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 39 AND airport_id = 19;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 40 AND airport_id = 19;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 24 AND airport_id = 19;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 25 AND airport_id = 19;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 226 AND airport_id = 19;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 38 AND airport_id = 19;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 39 AND airport_id = 20;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 40 AND airport_id = 20;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 24 AND airport_id = 20;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 25 AND airport_id = 20;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 226 AND airport_id = 20;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 38 AND airport_id = 20;
UPDATE airline_operations SET isc_amount = '90-180', isc_payable_to = 'AGI', last_updated = NOW() WHERE airline_id = 39 AND airport_id = 47;
UPDATE airline_operations SET isc_amount = '90-180', isc_payable_to = 'AGI', last_updated = NOW() WHERE airline_id = 40 AND airport_id = 47;
UPDATE airline_operations SET isc_amount = '90-180', isc_payable_to = 'AGI', last_updated = NOW() WHERE airline_id = 24 AND airport_id = 47;
UPDATE airline_operations SET isc_amount = '90-180', isc_payable_to = 'AGI', last_updated = NOW() WHERE airline_id = 25 AND airport_id = 47;
UPDATE airline_operations SET isc_amount = '90-180', isc_payable_to = 'AGI', last_updated = NOW() WHERE airline_id = 226 AND airport_id = 47;
UPDATE airline_operations SET isc_amount = '90-180', isc_payable_to = 'AGI', last_updated = NOW() WHERE airline_id = 38 AND airport_id = 47;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 39 AND airport_id = 15;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 40 AND airport_id = 15;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 24 AND airport_id = 15;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 25 AND airport_id = 15;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 226 AND airport_id = 15;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 38 AND airport_id = 15;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 39 AND airport_id = 14;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 40 AND airport_id = 14;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 24 AND airport_id = 14;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 25 AND airport_id = 14;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 226 AND airport_id = 14;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 38 AND airport_id = 14;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 39 AND airport_id = 5;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 40 AND airport_id = 5;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 24 AND airport_id = 5;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 25 AND airport_id = 5;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 226 AND airport_id = 5;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 38 AND airport_id = 5;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 39 AND airport_id = 22;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 40 AND airport_id = 22;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 24 AND airport_id = 22;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 25 AND airport_id = 22;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 226 AND airport_id = 22;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 38 AND airport_id = 22;
UPDATE airline_operations SET isc_amount = '90-180', isc_payable_to = 'AGI', last_updated = NOW() WHERE airline_id = 39 AND airport_id = 9;
UPDATE airline_operations SET isc_amount = '90-180', isc_payable_to = 'AGI', last_updated = NOW() WHERE airline_id = 40 AND airport_id = 9;
UPDATE airline_operations SET isc_amount = '90-180', isc_payable_to = 'AGI', last_updated = NOW() WHERE airline_id = 24 AND airport_id = 9;
UPDATE airline_operations SET isc_amount = '90-180', isc_payable_to = 'AGI', last_updated = NOW() WHERE airline_id = 25 AND airport_id = 9;
UPDATE airline_operations SET isc_amount = '90-180', isc_payable_to = 'AGI', last_updated = NOW() WHERE airline_id = 226 AND airport_id = 9;
UPDATE airline_operations SET isc_amount = '90-180', isc_payable_to = 'AGI', last_updated = NOW() WHERE airline_id = 38 AND airport_id = 9;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 39 AND airport_id = 17;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 40 AND airport_id = 17;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 24 AND airport_id = 17;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 25 AND airport_id = 17;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 226 AND airport_id = 17;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 38 AND airport_id = 17;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 39 AND airport_id = 37;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 40 AND airport_id = 37;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 24 AND airport_id = 37;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 25 AND airport_id = 37;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 226 AND airport_id = 37;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 38 AND airport_id = 37;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 39 AND airport_id = 54;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 40 AND airport_id = 54;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 24 AND airport_id = 54;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 25 AND airport_id = 54;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 226 AND airport_id = 54;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 38 AND airport_id = 54;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 39 AND airport_id = 1238;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 40 AND airport_id = 1238;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 24 AND airport_id = 1238;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 25 AND airport_id = 1238;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 226 AND airport_id = 1238;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 38 AND airport_id = 1238;
UPDATE airline_operations SET isc_amount = '90-180', isc_payable_to = 'AGI', last_updated = NOW() WHERE airline_id = 39 AND airport_id = 24;
UPDATE airline_operations SET isc_amount = '90-180', isc_payable_to = 'AGI', last_updated = NOW() WHERE airline_id = 40 AND airport_id = 24;
UPDATE airline_operations SET isc_amount = '90-180', isc_payable_to = 'AGI', last_updated = NOW() WHERE airline_id = 24 AND airport_id = 24;
UPDATE airline_operations SET isc_amount = '90-180', isc_payable_to = 'AGI', last_updated = NOW() WHERE airline_id = 25 AND airport_id = 24;
UPDATE airline_operations SET isc_amount = '90-180', isc_payable_to = 'AGI', last_updated = NOW() WHERE airline_id = 226 AND airport_id = 24;
UPDATE airline_operations SET isc_amount = '90-180', isc_payable_to = 'AGI', last_updated = NOW() WHERE airline_id = 38 AND airport_id = 24;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 39 AND airport_id = 44;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 40 AND airport_id = 44;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 24 AND airport_id = 44;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 25 AND airport_id = 44;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 226 AND airport_id = 44;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 38 AND airport_id = 44;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 39 AND airport_id = 43;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 40 AND airport_id = 43;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 24 AND airport_id = 43;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 25 AND airport_id = 43;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 226 AND airport_id = 43;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 38 AND airport_id = 43;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 39 AND airport_id = 41;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 40 AND airport_id = 41;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 24 AND airport_id = 41;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 25 AND airport_id = 41;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 226 AND airport_id = 41;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 38 AND airport_id = 41;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 39 AND airport_id = 10;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 40 AND airport_id = 10;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 24 AND airport_id = 10;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 25 AND airport_id = 10;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 226 AND airport_id = 10;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 38 AND airport_id = 10;
UPDATE airline_operations SET isc_amount = '90-180', isc_payable_to = 'AGI', last_updated = NOW() WHERE airline_id = 39 AND airport_id = 29;
UPDATE airline_operations SET isc_amount = '90-180', isc_payable_to = 'AGI', last_updated = NOW() WHERE airline_id = 40 AND airport_id = 29;
UPDATE airline_operations SET isc_amount = '90-180', isc_payable_to = 'AGI', last_updated = NOW() WHERE airline_id = 24 AND airport_id = 29;
UPDATE airline_operations SET isc_amount = '90-180', isc_payable_to = 'AGI', last_updated = NOW() WHERE airline_id = 25 AND airport_id = 29;
UPDATE airline_operations SET isc_amount = '90-180', isc_payable_to = 'AGI', last_updated = NOW() WHERE airline_id = 226 AND airport_id = 29;
UPDATE airline_operations SET isc_amount = '90-180', isc_payable_to = 'AGI', last_updated = NOW() WHERE airline_id = 38 AND airport_id = 29;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 39 AND airport_id = 28;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 40 AND airport_id = 28;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 24 AND airport_id = 28;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 25 AND airport_id = 28;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 226 AND airport_id = 28;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 38 AND airport_id = 28;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 39 AND airport_id = 65;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 40 AND airport_id = 65;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 24 AND airport_id = 65;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 25 AND airport_id = 65;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 226 AND airport_id = 65;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 38 AND airport_id = 65;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 39 AND airport_id = 33;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 40 AND airport_id = 33;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 24 AND airport_id = 33;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 25 AND airport_id = 33;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 226 AND airport_id = 33;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 38 AND airport_id = 33;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 39 AND airport_id = 23;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 40 AND airport_id = 23;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 24 AND airport_id = 23;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 25 AND airport_id = 23;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 226 AND airport_id = 23;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 38 AND airport_id = 23;
UPDATE airline_operations SET isc_amount = '90-180', isc_payable_to = 'AGI', last_updated = NOW() WHERE airline_id = 39 AND airport_id = 30;
UPDATE airline_operations SET isc_amount = '90-180', isc_payable_to = 'AGI', last_updated = NOW() WHERE airline_id = 40 AND airport_id = 30;
UPDATE airline_operations SET isc_amount = '90-180', isc_payable_to = 'AGI', last_updated = NOW() WHERE airline_id = 24 AND airport_id = 30;
UPDATE airline_operations SET isc_amount = '90-180', isc_payable_to = 'AGI', last_updated = NOW() WHERE airline_id = 25 AND airport_id = 30;
UPDATE airline_operations SET isc_amount = '90-180', isc_payable_to = 'AGI', last_updated = NOW() WHERE airline_id = 226 AND airport_id = 30;
UPDATE airline_operations SET isc_amount = '90-180', isc_payable_to = 'AGI', last_updated = NOW() WHERE airline_id = 38 AND airport_id = 30;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 39 AND airport_id = 42;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 40 AND airport_id = 42;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 24 AND airport_id = 42;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 25 AND airport_id = 42;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 226 AND airport_id = 42;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 38 AND airport_id = 42;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 39 AND airport_id = 56;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 40 AND airport_id = 56;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 24 AND airport_id = 56;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 25 AND airport_id = 56;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 226 AND airport_id = 56;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 38 AND airport_id = 56;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 39 AND airport_id = 26;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 40 AND airport_id = 26;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 24 AND airport_id = 26;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 25 AND airport_id = 26;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 226 AND airport_id = 26;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 38 AND airport_id = 26;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 39 AND airport_id = 27;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 40 AND airport_id = 27;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 24 AND airport_id = 27;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 25 AND airport_id = 27;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 226 AND airport_id = 27;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 38 AND airport_id = 27;
UPDATE airline_operations SET isc_amount = '90-180', isc_payable_to = 'AGI', last_updated = NOW() WHERE airline_id = 39 AND airport_id = 1353;
UPDATE airline_operations SET isc_amount = '90-180', isc_payable_to = 'AGI', last_updated = NOW() WHERE airline_id = 40 AND airport_id = 1353;
UPDATE airline_operations SET isc_amount = '90-180', isc_payable_to = 'AGI', last_updated = NOW() WHERE airline_id = 24 AND airport_id = 1353;
UPDATE airline_operations SET isc_amount = '90-180', isc_payable_to = 'AGI', last_updated = NOW() WHERE airline_id = 25 AND airport_id = 1353;
UPDATE airline_operations SET isc_amount = '90-180', isc_payable_to = 'AGI', last_updated = NOW() WHERE airline_id = 226 AND airport_id = 1353;
UPDATE airline_operations SET isc_amount = '90-180', isc_payable_to = 'AGI', last_updated = NOW() WHERE airline_id = 38 AND airport_id = 1353;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 39 AND airport_id = 64;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 40 AND airport_id = 64;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 24 AND airport_id = 64;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 25 AND airport_id = 64;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 226 AND airport_id = 64;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 38 AND airport_id = 64;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 39 AND airport_id = 66;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 40 AND airport_id = 66;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 24 AND airport_id = 66;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 25 AND airport_id = 66;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 226 AND airport_id = 66;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 38 AND airport_id = 66;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 39 AND airport_id = 67;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 40 AND airport_id = 67;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 24 AND airport_id = 67;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 25 AND airport_id = 67;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 226 AND airport_id = 67;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 38 AND airport_id = 67;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 39 AND airport_id = 69;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 40 AND airport_id = 69;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 24 AND airport_id = 69;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 25 AND airport_id = 69;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 226 AND airport_id = 69;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 38 AND airport_id = 69;
UPDATE airline_operations SET isc_amount = '90-180', isc_payable_to = 'AGI', last_updated = NOW() WHERE airline_id = 39 AND airport_id = 68;
UPDATE airline_operations SET isc_amount = '90-180', isc_payable_to = 'AGI', last_updated = NOW() WHERE airline_id = 40 AND airport_id = 68;
UPDATE airline_operations SET isc_amount = '90-180', isc_payable_to = 'AGI', last_updated = NOW() WHERE airline_id = 24 AND airport_id = 68;
UPDATE airline_operations SET isc_amount = '90-180', isc_payable_to = 'AGI', last_updated = NOW() WHERE airline_id = 25 AND airport_id = 68;
UPDATE airline_operations SET isc_amount = '90-180', isc_payable_to = 'AGI', last_updated = NOW() WHERE airline_id = 226 AND airport_id = 68;
UPDATE airline_operations SET isc_amount = '90-180', isc_payable_to = 'AGI', last_updated = NOW() WHERE airline_id = 38 AND airport_id = 68;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 39 AND airport_id = 63;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 40 AND airport_id = 63;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 24 AND airport_id = 63;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 25 AND airport_id = 63;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 226 AND airport_id = 63;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 38 AND airport_id = 63;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 39 AND airport_id = 61;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 40 AND airport_id = 61;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 24 AND airport_id = 61;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 25 AND airport_id = 61;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 226 AND airport_id = 61;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 38 AND airport_id = 61;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 39 AND airport_id = 55;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 40 AND airport_id = 55;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 24 AND airport_id = 55;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 25 AND airport_id = 55;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 226 AND airport_id = 55;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 38 AND airport_id = 55;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 39 AND airport_id = 60;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 40 AND airport_id = 60;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 24 AND airport_id = 60;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 25 AND airport_id = 60;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 226 AND airport_id = 60;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 38 AND airport_id = 60;
UPDATE airline_operations SET isc_amount = '90-180', isc_payable_to = 'AGI', last_updated = NOW() WHERE airline_id = 39 AND airport_id = 77;
UPDATE airline_operations SET isc_amount = '90-180', isc_payable_to = 'AGI', last_updated = NOW() WHERE airline_id = 40 AND airport_id = 77;
UPDATE airline_operations SET isc_amount = '90-180', isc_payable_to = 'AGI', last_updated = NOW() WHERE airline_id = 24 AND airport_id = 77;
UPDATE airline_operations SET isc_amount = '90-180', isc_payable_to = 'AGI', last_updated = NOW() WHERE airline_id = 25 AND airport_id = 77;
UPDATE airline_operations SET isc_amount = '90-180', isc_payable_to = 'AGI', last_updated = NOW() WHERE airline_id = 226 AND airport_id = 77;
UPDATE airline_operations SET isc_amount = '90-180', isc_payable_to = 'AGI', last_updated = NOW() WHERE airline_id = 38 AND airport_id = 77;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 39 AND airport_id = 75;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 40 AND airport_id = 75;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 24 AND airport_id = 75;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 25 AND airport_id = 75;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 226 AND airport_id = 75;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 38 AND airport_id = 75;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 39 AND airport_id = 88;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 40 AND airport_id = 88;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 24 AND airport_id = 88;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 25 AND airport_id = 88;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 226 AND airport_id = 88;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 38 AND airport_id = 88;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 39 AND airport_id = 86;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 40 AND airport_id = 86;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 24 AND airport_id = 86;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 25 AND airport_id = 86;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 226 AND airport_id = 86;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 38 AND airport_id = 86;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 39 AND airport_id = 90;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 40 AND airport_id = 90;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 24 AND airport_id = 90;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 25 AND airport_id = 90;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 226 AND airport_id = 90;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 38 AND airport_id = 90;
UPDATE airline_operations SET isc_amount = '90-180', isc_payable_to = 'AGI', last_updated = NOW() WHERE airline_id = 39 AND airport_id = 92;
UPDATE airline_operations SET isc_amount = '90-180', isc_payable_to = 'AGI', last_updated = NOW() WHERE airline_id = 40 AND airport_id = 92;
UPDATE airline_operations SET isc_amount = '90-180', isc_payable_to = 'AGI', last_updated = NOW() WHERE airline_id = 24 AND airport_id = 92;
UPDATE airline_operations SET isc_amount = '90-180', isc_payable_to = 'AGI', last_updated = NOW() WHERE airline_id = 25 AND airport_id = 92;
UPDATE airline_operations SET isc_amount = '90-180', isc_payable_to = 'AGI', last_updated = NOW() WHERE airline_id = 226 AND airport_id = 92;
UPDATE airline_operations SET isc_amount = '90-180', isc_payable_to = 'AGI', last_updated = NOW() WHERE airline_id = 38 AND airport_id = 92;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 39 AND airport_id = 91;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 40 AND airport_id = 91;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 24 AND airport_id = 91;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 25 AND airport_id = 91;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 226 AND airport_id = 91;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 38 AND airport_id = 91;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 39 AND airport_id = 93;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 40 AND airport_id = 93;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 24 AND airport_id = 93;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 25 AND airport_id = 93;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 226 AND airport_id = 93;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 38 AND airport_id = 93;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 39 AND airport_id = 25;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 40 AND airport_id = 25;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 24 AND airport_id = 25;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 25 AND airport_id = 25;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 226 AND airport_id = 25;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 38 AND airport_id = 25;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 39 AND airport_id = 45;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 40 AND airport_id = 45;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 24 AND airport_id = 45;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 25 AND airport_id = 45;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 226 AND airport_id = 45;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 38 AND airport_id = 45;
UPDATE airline_operations SET isc_amount = '90-180', isc_payable_to = 'AGI', last_updated = NOW() WHERE airline_id = 39 AND airport_id = 114;
UPDATE airline_operations SET isc_amount = '90-180', isc_payable_to = 'AGI', last_updated = NOW() WHERE airline_id = 40 AND airport_id = 114;
UPDATE airline_operations SET isc_amount = '90-180', isc_payable_to = 'AGI', last_updated = NOW() WHERE airline_id = 24 AND airport_id = 114;
UPDATE airline_operations SET isc_amount = '90-180', isc_payable_to = 'AGI', last_updated = NOW() WHERE airline_id = 25 AND airport_id = 114;
UPDATE airline_operations SET isc_amount = '90-180', isc_payable_to = 'AGI', last_updated = NOW() WHERE airline_id = 226 AND airport_id = 114;
UPDATE airline_operations SET isc_amount = '90-180', isc_payable_to = 'AGI', last_updated = NOW() WHERE airline_id = 38 AND airport_id = 114;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 39 AND airport_id = 46;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 40 AND airport_id = 46;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 24 AND airport_id = 46;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 25 AND airport_id = 46;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 226 AND airport_id = 46;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 38 AND airport_id = 46;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 39 AND airport_id = 103;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 40 AND airport_id = 103;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 24 AND airport_id = 103;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 25 AND airport_id = 103;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 226 AND airport_id = 103;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 38 AND airport_id = 103;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 39 AND airport_id = 102;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 40 AND airport_id = 102;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 24 AND airport_id = 102;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 25 AND airport_id = 102;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 226 AND airport_id = 102;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 38 AND airport_id = 102;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 39 AND airport_id = 1169;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 40 AND airport_id = 1169;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 24 AND airport_id = 1169;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 25 AND airport_id = 1169;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 226 AND airport_id = 1169;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 38 AND airport_id = 1169;
UPDATE airline_operations SET isc_amount = '90-180', isc_payable_to = 'AGI', last_updated = NOW() WHERE airline_id = 39 AND airport_id = 111;
UPDATE airline_operations SET isc_amount = '90-180', isc_payable_to = 'AGI', last_updated = NOW() WHERE airline_id = 40 AND airport_id = 111;
UPDATE airline_operations SET isc_amount = '90-180', isc_payable_to = 'AGI', last_updated = NOW() WHERE airline_id = 24 AND airport_id = 111;
UPDATE airline_operations SET isc_amount = '90-180', isc_payable_to = 'AGI', last_updated = NOW() WHERE airline_id = 25 AND airport_id = 111;
UPDATE airline_operations SET isc_amount = '90-180', isc_payable_to = 'AGI', last_updated = NOW() WHERE airline_id = 226 AND airport_id = 111;
UPDATE airline_operations SET isc_amount = '90-180', isc_payable_to = 'AGI', last_updated = NOW() WHERE airline_id = 38 AND airport_id = 111;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 39 AND airport_id = 96;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 40 AND airport_id = 96;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 24 AND airport_id = 96;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 25 AND airport_id = 96;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 226 AND airport_id = 96;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 38 AND airport_id = 96;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 39 AND airport_id = 94;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 40 AND airport_id = 94;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 24 AND airport_id = 94;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 25 AND airport_id = 94;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 226 AND airport_id = 94;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 38 AND airport_id = 94;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 39 AND airport_id = 95;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 40 AND airport_id = 95;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 24 AND airport_id = 95;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 25 AND airport_id = 95;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 226 AND airport_id = 95;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 38 AND airport_id = 95;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 39 AND airport_id = 97;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 40 AND airport_id = 97;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 24 AND airport_id = 97;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 25 AND airport_id = 97;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 226 AND airport_id = 97;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 38 AND airport_id = 97;
UPDATE airline_operations SET isc_amount = '90-180', isc_payable_to = 'AGI', last_updated = NOW() WHERE airline_id = 39 AND airport_id = 52;
UPDATE airline_operations SET isc_amount = '90-180', isc_payable_to = 'AGI', last_updated = NOW() WHERE airline_id = 40 AND airport_id = 52;
UPDATE airline_operations SET isc_amount = '90-180', isc_payable_to = 'AGI', last_updated = NOW() WHERE airline_id = 24 AND airport_id = 52;
UPDATE airline_operations SET isc_amount = '90-180', isc_payable_to = 'AGI', last_updated = NOW() WHERE airline_id = 25 AND airport_id = 52;
UPDATE airline_operations SET isc_amount = '90-180', isc_payable_to = 'AGI', last_updated = NOW() WHERE airline_id = 226 AND airport_id = 52;
UPDATE airline_operations SET isc_amount = '90-180', isc_payable_to = 'AGI', last_updated = NOW() WHERE airline_id = 38 AND airport_id = 52;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 39 AND airport_id = 1617;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 40 AND airport_id = 1617;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 24 AND airport_id = 1617;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 25 AND airport_id = 1617;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 226 AND airport_id = 1617;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 38 AND airport_id = 1617;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 39 AND airport_id = 50;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 40 AND airport_id = 50;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 24 AND airport_id = 50;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 25 AND airport_id = 50;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 226 AND airport_id = 50;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 38 AND airport_id = 50;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 39 AND airport_id = 51;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 40 AND airport_id = 51;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 24 AND airport_id = 51;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 25 AND airport_id = 51;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 226 AND airport_id = 51;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 38 AND airport_id = 51;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 39 AND airport_id = 49;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 40 AND airport_id = 49;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 24 AND airport_id = 49;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 25 AND airport_id = 49;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 226 AND airport_id = 49;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 38 AND airport_id = 49;
UPDATE airline_operations SET isc_amount = '90-180', isc_payable_to = 'AGI', last_updated = NOW() WHERE airline_id = 39 AND airport_id = 21;
UPDATE airline_operations SET isc_amount = '90-180', isc_payable_to = 'AGI', last_updated = NOW() WHERE airline_id = 40 AND airport_id = 21;
UPDATE airline_operations SET isc_amount = '90-180', isc_payable_to = 'AGI', last_updated = NOW() WHERE airline_id = 24 AND airport_id = 21;
UPDATE airline_operations SET isc_amount = '90-180', isc_payable_to = 'AGI', last_updated = NOW() WHERE airline_id = 25 AND airport_id = 21;
UPDATE airline_operations SET isc_amount = '90-180', isc_payable_to = 'AGI', last_updated = NOW() WHERE airline_id = 226 AND airport_id = 21;
UPDATE airline_operations SET isc_amount = '90-180', isc_payable_to = 'AGI', last_updated = NOW() WHERE airline_id = 38 AND airport_id = 21;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 39 AND airport_id = 48;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 40 AND airport_id = 48;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 24 AND airport_id = 48;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 25 AND airport_id = 48;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 226 AND airport_id = 48;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 38 AND airport_id = 48;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 39 AND airport_id = 107;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 40 AND airport_id = 107;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 24 AND airport_id = 107;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 25 AND airport_id = 107;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 226 AND airport_id = 107;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 38 AND airport_id = 107;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 39 AND airport_id = 98;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 40 AND airport_id = 98;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 24 AND airport_id = 98;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 25 AND airport_id = 98;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 226 AND airport_id = 98;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 38 AND airport_id = 98;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 39 AND airport_id = 100;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 40 AND airport_id = 100;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 24 AND airport_id = 100;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 25 AND airport_id = 100;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 226 AND airport_id = 100;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 38 AND airport_id = 100;
UPDATE airline_operations SET isc_amount = '90-180', isc_payable_to = 'AGI', last_updated = NOW() WHERE airline_id = 39 AND airport_id = 101;
UPDATE airline_operations SET isc_amount = '90-180', isc_payable_to = 'AGI', last_updated = NOW() WHERE airline_id = 40 AND airport_id = 101;
UPDATE airline_operations SET isc_amount = '90-180', isc_payable_to = 'AGI', last_updated = NOW() WHERE airline_id = 24 AND airport_id = 101;
UPDATE airline_operations SET isc_amount = '90-180', isc_payable_to = 'AGI', last_updated = NOW() WHERE airline_id = 25 AND airport_id = 101;
UPDATE airline_operations SET isc_amount = '90-180', isc_payable_to = 'AGI', last_updated = NOW() WHERE airline_id = 226 AND airport_id = 101;
UPDATE airline_operations SET isc_amount = '90-180', isc_payable_to = 'AGI', last_updated = NOW() WHERE airline_id = 38 AND airport_id = 101;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 39 AND airport_id = 122;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 40 AND airport_id = 122;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 24 AND airport_id = 122;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 25 AND airport_id = 122;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 226 AND airport_id = 122;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 38 AND airport_id = 122;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 39 AND airport_id = 121;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 40 AND airport_id = 121;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 24 AND airport_id = 121;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 25 AND airport_id = 121;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 226 AND airport_id = 121;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 38 AND airport_id = 121;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 39 AND airport_id = 123;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 40 AND airport_id = 123;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 24 AND airport_id = 123;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 25 AND airport_id = 123;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 226 AND airport_id = 123;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 38 AND airport_id = 123;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 39 AND airport_id = 1558;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 40 AND airport_id = 1558;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 24 AND airport_id = 1558;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 25 AND airport_id = 1558;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 226 AND airport_id = 1558;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 38 AND airport_id = 1558;
UPDATE airline_operations SET isc_amount = '90-180', isc_payable_to = 'AGI', last_updated = NOW() WHERE airline_id = 39 AND airport_id = 129;
UPDATE airline_operations SET isc_amount = '90-180', isc_payable_to = 'AGI', last_updated = NOW() WHERE airline_id = 40 AND airport_id = 129;
UPDATE airline_operations SET isc_amount = '90-180', isc_payable_to = 'AGI', last_updated = NOW() WHERE airline_id = 24 AND airport_id = 129;
UPDATE airline_operations SET isc_amount = '90-180', isc_payable_to = 'AGI', last_updated = NOW() WHERE airline_id = 25 AND airport_id = 129;
UPDATE airline_operations SET isc_amount = '90-180', isc_payable_to = 'AGI', last_updated = NOW() WHERE airline_id = 226 AND airport_id = 129;
UPDATE airline_operations SET isc_amount = '90-180', isc_payable_to = 'AGI', last_updated = NOW() WHERE airline_id = 38 AND airport_id = 129;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 39 AND airport_id = 130;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 40 AND airport_id = 130;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 24 AND airport_id = 130;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 25 AND airport_id = 130;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 226 AND airport_id = 130;
UPDATE airline_operations SET isc_amount = '70-140', isc_payable_to = 'dnata Cargo USA', last_updated = NOW() WHERE airline_id = 38 AND airport_id = 130;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 39 AND airport_id = 132;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 40 AND airport_id = 132;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 24 AND airport_id = 132;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 25 AND airport_id = 132;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 226 AND airport_id = 132;
UPDATE airline_operations SET isc_amount = '75-150', isc_payable_to = 'Swissport', last_updated = NOW() WHERE airline_id = 38 AND airport_id = 132;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 39 AND airport_id = 131;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 40 AND airport_id = 131;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 24 AND airport_id = 131;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 25 AND airport_id = 131;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 226 AND airport_id = 131;
UPDATE airline_operations SET isc_amount = '80-160', isc_payable_to = 'WFS', last_updated = NOW() WHERE airline_id = 38 AND airport_id = 131;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 39 AND airport_id = 18;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 40 AND airport_id = 18;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 24 AND airport_id = 18;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 25 AND airport_id = 18;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 226 AND airport_id = 18;
UPDATE airline_operations SET isc_amount = '85-170', isc_payable_to = 'Menzies', last_updated = NOW() WHERE airline_id = 38 AND airport_id = 18;
