-- Airline Operations Ground Handler & Contact Patch
  -- Generated: 2026-03-24T21:09:20.424Z
  -- Updates handler names and contact info for EK, QR, LH, AF, TK, 5Y across all airports
  -- Safe to re-run: uses UPDATE WHERE, will not insert or delete rows

  UPDATE public.airline_operations SET isc_payable_to = 'Swissport', contact_number = '404-767-8785', contact_email = 'ATLLHOPS@SWISSPORT.COM' WHERE airline_id = 24 AND airport_id = 1;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport', contact_number = '310-417-9126', contact_email = 'LAXLHOPS@SWISSPORT.COM' WHERE airline_id = 24 AND airport_id = 2;
UPDATE public.airline_operations SET isc_payable_to = 'WFS', contact_number = '+1 773-686-5700', contact_email = 'ordlhimport@wfs.aero' WHERE airline_id = 24 AND airport_id = 3;
UPDATE public.airline_operations SET isc_payable_to = 'WFS', contact_number = '469-629-0605', contact_email = 'dfwlhimport@wfs.aero' WHERE airline_id = 24 AND airport_id = 4;
UPDATE public.airline_operations SET isc_payable_to = 'Air General', contact_number = '303-342-3502', contact_email = 'dencargo@airgeneral.com' WHERE airline_id = 24 AND airport_id = 5;
UPDATE public.airline_operations SET isc_payable_to = 'delta', contact_number = '718-289-7226', contact_email = 'jfkimport@dlh.de' WHERE airline_id = 24 AND airport_id = 6;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport', contact_number = '650-874-8300', contact_email = 'sfotklhops@swissport.com' WHERE airline_id = 24 AND airport_id = 7;
UPDATE public.airline_operations SET isc_payable_to = 'Menzies', contact_number = '+1 206-243-6157', contact_email = 'seaimport@menziesaviation.com' WHERE airline_id = 24 AND airport_id = 8;
UPDATE public.airline_operations SET isc_payable_to = 'AGI' WHERE airline_id = 24 AND airport_id = 9;
UPDATE public.airline_operations SET isc_payable_to = 'Menzies' WHERE airline_id = 24 AND airport_id = 10;
UPDATE public.airline_operations SET isc_payable_to = 'WFS', contact_number = '305-871-5365', contact_email = 'miaimport@dlh.de' WHERE airline_id = 24 AND airport_id = 11;
UPDATE public.airline_operations SET isc_payable_to = 'WFS', contact_number = '281-233-3110', contact_email = 'iahimport@wfs.aero' WHERE airline_id = 24 AND airport_id = 12;
UPDATE public.airline_operations SET isc_payable_to = 'WFS', contact_number = '617-766-3306', contact_email = 'BOSimportOPS@wfs.aero' WHERE airline_id = 24 AND airport_id = 13;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport' WHERE airline_id = 24 AND airport_id = 14;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport', contact_number = '215-365-0200', contact_email = 'PHLLHOPS@SWISSPORT.COM' WHERE airline_id = 24 AND airport_id = 16;
UPDATE public.airline_operations SET isc_payable_to = 'WFS', contact_number = '801-575-2760', contact_email = 'slcimport@wfs.aero' WHERE airline_id = 24 AND airport_id = 17;
UPDATE public.airline_operations SET isc_payable_to = 'Menzies' WHERE airline_id = 24 AND airport_id = 18;
UPDATE public.airline_operations SET isc_payable_to = 'WFS', contact_number = '+1 703-572-7530' WHERE airline_id = 24 AND airport_id = 19;
UPDATE public.airline_operations SET isc_payable_to = 'Menzies' WHERE airline_id = 24 AND airport_id = 20;
UPDATE public.airline_operations SET isc_payable_to = 'AGI' WHERE airline_id = 24 AND airport_id = 21;
UPDATE public.airline_operations SET isc_payable_to = 'Menzies' WHERE airline_id = 24 AND airport_id = 22;
UPDATE public.airline_operations SET isc_payable_to = 'Menzies' WHERE airline_id = 24 AND airport_id = 23;
UPDATE public.airline_operations SET isc_payable_to = 'AGI' WHERE airline_id = 24 AND airport_id = 24;
UPDATE public.airline_operations SET isc_payable_to = 'WFS' WHERE airline_id = 24 AND airport_id = 25;
UPDATE public.airline_operations SET isc_payable_to = 'WFS' WHERE airline_id = 24 AND airport_id = 26;
UPDATE public.airline_operations SET isc_payable_to = 'Menzies' WHERE airline_id = 24 AND airport_id = 27;
UPDATE public.airline_operations SET isc_payable_to = 'WFS' WHERE airline_id = 24 AND airport_id = 28;
UPDATE public.airline_operations SET isc_payable_to = 'AGI' WHERE airline_id = 24 AND airport_id = 29;
UPDATE public.airline_operations SET isc_payable_to = 'AGI' WHERE airline_id = 24 AND airport_id = 30;
UPDATE public.airline_operations SET isc_payable_to = 'WFS' WHERE airline_id = 24 AND airport_id = 33;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport' WHERE airline_id = 24 AND airport_id = 37;
UPDATE public.airline_operations SET isc_payable_to = 'WFS' WHERE airline_id = 24 AND airport_id = 41;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport' WHERE airline_id = 24 AND airport_id = 43;
UPDATE public.airline_operations SET isc_payable_to = 'WFS', contact_number = '412-472-3300', contact_email = 'pitimport@wfs.aero' WHERE airline_id = 24 AND airport_id = 44;
UPDATE public.airline_operations SET isc_payable_to = 'Menzies' WHERE airline_id = 24 AND airport_id = 45;
UPDATE public.airline_operations SET isc_payable_to = 'AGI' WHERE airline_id = 24 AND airport_id = 47;
UPDATE public.airline_operations SET isc_payable_to = 'Menzies' WHERE airline_id = 24 AND airport_id = 49;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport' WHERE airline_id = 24 AND airport_id = 50;
UPDATE public.airline_operations SET isc_payable_to = 'WFS' WHERE airline_id = 24 AND airport_id = 51;
UPDATE public.airline_operations SET isc_payable_to = 'AGI' WHERE airline_id = 24 AND airport_id = 52;
UPDATE public.airline_operations SET isc_payable_to = 'WFS' WHERE airline_id = 24 AND airport_id = 54;
UPDATE public.airline_operations SET isc_payable_to = 'WFS' WHERE airline_id = 24 AND airport_id = 55;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport' WHERE airline_id = 24 AND airport_id = 56;
UPDATE public.airline_operations SET isc_payable_to = 'Menzies' WHERE airline_id = 24 AND airport_id = 60;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport' WHERE airline_id = 24 AND airport_id = 61;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport' WHERE airline_id = 24 AND airport_id = 65;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport' WHERE airline_id = 24 AND airport_id = 66;
UPDATE public.airline_operations SET isc_payable_to = 'WFS' WHERE airline_id = 24 AND airport_id = 67;
UPDATE public.airline_operations SET isc_payable_to = 'AGI' WHERE airline_id = 24 AND airport_id = 68;
UPDATE public.airline_operations SET isc_payable_to = 'Menzies' WHERE airline_id = 24 AND airport_id = 69;
UPDATE public.airline_operations SET isc_payable_to = 'AGI' WHERE airline_id = 24 AND airport_id = 77;
UPDATE public.airline_operations SET isc_payable_to = 'WFS' WHERE airline_id = 24 AND airport_id = 86;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport' WHERE airline_id = 24 AND airport_id = 88;
UPDATE public.airline_operations SET isc_payable_to = 'Menzies' WHERE airline_id = 24 AND airport_id = 90;
UPDATE public.airline_operations SET isc_payable_to = 'AGI' WHERE airline_id = 24 AND airport_id = 92;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport' WHERE airline_id = 24 AND airport_id = 93;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport' WHERE airline_id = 24 AND airport_id = 94;
UPDATE public.airline_operations SET isc_payable_to = 'WFS' WHERE airline_id = 24 AND airport_id = 95;
UPDATE public.airline_operations SET isc_payable_to = 'Menzies' WHERE airline_id = 24 AND airport_id = 97;
UPDATE public.airline_operations SET isc_payable_to = 'WFS' WHERE airline_id = 24 AND airport_id = 98;
UPDATE public.airline_operations SET isc_payable_to = 'Menzies' WHERE airline_id = 24 AND airport_id = 100;
UPDATE public.airline_operations SET isc_payable_to = 'AGI' WHERE airline_id = 24 AND airport_id = 101;
UPDATE public.airline_operations SET isc_payable_to = 'WFS' WHERE airline_id = 24 AND airport_id = 102;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport' WHERE airline_id = 24 AND airport_id = 103;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport' WHERE airline_id = 24 AND airport_id = 107;
UPDATE public.airline_operations SET isc_payable_to = 'AGI' WHERE airline_id = 24 AND airport_id = 111;
UPDATE public.airline_operations SET isc_payable_to = 'AGI' WHERE airline_id = 24 AND airport_id = 114;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport' WHERE airline_id = 24 AND airport_id = 121;
UPDATE public.airline_operations SET isc_payable_to = 'WFS' WHERE airline_id = 24 AND airport_id = 123;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport', contact_number = '973-681-3376', contact_email = 'ewrlhops@swissport.com' WHERE airline_id = 24 AND airport_id = 126;
UPDATE public.airline_operations SET isc_payable_to = 'AGI' WHERE airline_id = 24 AND airport_id = 129;
UPDATE public.airline_operations SET isc_payable_to = 'WFS' WHERE airline_id = 24 AND airport_id = 131;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport' WHERE airline_id = 24 AND airport_id = 132;
UPDATE public.airline_operations SET isc_payable_to = 'Menzies' WHERE airline_id = 24 AND airport_id = 1169;
UPDATE public.airline_operations SET isc_payable_to = 'Menzies' WHERE airline_id = 24 AND airport_id = 1238;
UPDATE public.airline_operations SET isc_payable_to = 'AGI' WHERE airline_id = 24 AND airport_id = 1353;
UPDATE public.airline_operations SET isc_payable_to = 'Menzies' WHERE airline_id = 24 AND airport_id = 1558;
UPDATE public.airline_operations SET isc_payable_to = 'WFS', contact_number = '404-763-1221', contact_email = 'atlafimport@wfs.aero' WHERE airline_id = 25 AND airport_id = 1;
UPDATE public.airline_operations SET isc_payable_to = 'wfs', contact_number = '310-646-3620 EXT 804', contact_email = 'LAXAFOP@WFS.AERO' WHERE airline_id = 25 AND airport_id = 2;
UPDATE public.airline_operations SET isc_payable_to = 'WFS', contact_number = '+1 773-686-5700', contact_email = 'ordafimport@wfs.aero' WHERE airline_id = 25 AND airport_id = 3;
UPDATE public.airline_operations SET isc_payable_to = 'WFS', contact_number = '469-629-0605', contact_email = 'dfwafimport@wfs.aero' WHERE airline_id = 25 AND airport_id = 4;
UPDATE public.airline_operations SET isc_payable_to = 'WFS' WHERE airline_id = 25 AND airport_id = 5;
UPDATE public.airline_operations SET isc_payable_to = 'delta / wfs', contact_number = 'WFS 718-208-4297 // 800-556-9000/ DELTA 800 352 2746 // AF JFK 718 208 4397 KLM-1800-352-2746', contact_email = 'CUSTOMERSERVICE.JFK@AFKLMPCARGO.COM // DLCARGO@DELTA.COM' WHERE airline_id = 25 AND airport_id = 6;
UPDATE public.airline_operations SET isc_payable_to = 'MAC CARGO', contact_number = '650-737-4881', contact_email = 'sfomaccargo@maccargo.com' WHERE airline_id = 25 AND airport_id = 7;
UPDATE public.airline_operations SET isc_payable_to = 'Menzies', contact_number = '+1 206-243-6157', contact_email = 'seaimport@menziesaviation.com' WHERE airline_id = 25 AND airport_id = 8;
UPDATE public.airline_operations SET isc_payable_to = 'AGI' WHERE airline_id = 25 AND airport_id = 9;
UPDATE public.airline_operations SET isc_payable_to = 'Menzies' WHERE airline_id = 25 AND airport_id = 10;
UPDATE public.airline_operations SET isc_payable_to = 'wfs', contact_number = '3058742450 // 3058693614', contact_email = '"Negro, Rosa Maria (MIA CA QS) - AF <ronegro@airfrance.fr>  Rocio Jorge <Rocio.Jorge@wfs.aero>; Dealvarez-ext@airfrance.fr; Salman Nabil (TEU) <sb@teuinc.com>; customerservice.seusa@afklmpcargo.com; AFMIA <afmia@wfs.aero>; sequote@afkldlcargo.com Negro, Rosa Maria (MIA CA QS) - AF <ronegro@airfrance.fr>  MIACARGO@THY.COM; COUNTERIMPORT@LATAM.COM"' WHERE airline_id = 25 AND airport_id = 11;
UPDATE public.airline_operations SET isc_payable_to = 'WFS', contact_number = '281-233-3110', contact_email = 'iahimport@wfs.aero' WHERE airline_id = 25 AND airport_id = 12;
UPDATE public.airline_operations SET isc_payable_to = 'DELTA', contact_number = '617-561-2600' WHERE airline_id = 25 AND airport_id = 13;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport' WHERE airline_id = 25 AND airport_id = 14;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport', contact_number = '215-365-0200', contact_email = 'PHLAFOPS@SWISSPORT.COM' WHERE airline_id = 25 AND airport_id = 16;
UPDATE public.airline_operations SET isc_payable_to = 'WFS', contact_number = '801-575-2760', contact_email = 'slcimport@wfs.aero' WHERE airline_id = 25 AND airport_id = 17;
UPDATE public.airline_operations SET isc_payable_to = 'Menzies' WHERE airline_id = 25 AND airport_id = 18;
UPDATE public.airline_operations SET isc_payable_to = 'WFS', contact_number = '+1 703-572-7530' WHERE airline_id = 25 AND airport_id = 19;
UPDATE public.airline_operations SET isc_payable_to = 'Menzies' WHERE airline_id = 25 AND airport_id = 20;
UPDATE public.airline_operations SET isc_payable_to = 'AGI' WHERE airline_id = 25 AND airport_id = 21;
UPDATE public.airline_operations SET isc_payable_to = 'Menzies' WHERE airline_id = 25 AND airport_id = 22;
UPDATE public.airline_operations SET isc_payable_to = 'Menzies' WHERE airline_id = 25 AND airport_id = 23;
UPDATE public.airline_operations SET isc_payable_to = 'FORWARDAIR', contact_number = '844-811-8889', contact_email = 'custserv@forwardair.com; tcalvert@forwardair.com' WHERE airline_id = 25 AND airport_id = 24;
UPDATE public.airline_operations SET isc_payable_to = 'WFS' WHERE airline_id = 25 AND airport_id = 25;
UPDATE public.airline_operations SET isc_payable_to = 'WFS' WHERE airline_id = 25 AND airport_id = 26;
UPDATE public.airline_operations SET isc_payable_to = 'Menzies' WHERE airline_id = 25 AND airport_id = 27;
UPDATE public.airline_operations SET isc_payable_to = 'WFS', contact_number = '619-400-2200', contact_email = 'sanimport@wfs.aero' WHERE airline_id = 25 AND airport_id = 28;
UPDATE public.airline_operations SET isc_payable_to = 'AGI' WHERE airline_id = 25 AND airport_id = 29;
UPDATE public.airline_operations SET isc_payable_to = 'AGI' WHERE airline_id = 25 AND airport_id = 30;
UPDATE public.airline_operations SET isc_payable_to = 'WFS' WHERE airline_id = 25 AND airport_id = 33;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport' WHERE airline_id = 25 AND airport_id = 37;
UPDATE public.airline_operations SET isc_payable_to = 'WFS' WHERE airline_id = 25 AND airport_id = 41;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport' WHERE airline_id = 25 AND airport_id = 43;
UPDATE public.airline_operations SET isc_payable_to = 'WFS', contact_number = '412-472-3300', contact_email = 'pitimport@wfs.aero' WHERE airline_id = 25 AND airport_id = 44;
UPDATE public.airline_operations SET isc_payable_to = 'Menzies' WHERE airline_id = 25 AND airport_id = 45;
UPDATE public.airline_operations SET isc_payable_to = 'AGI' WHERE airline_id = 25 AND airport_id = 47;
UPDATE public.airline_operations SET isc_payable_to = 'Menzies' WHERE airline_id = 25 AND airport_id = 49;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport' WHERE airline_id = 25 AND airport_id = 50;
UPDATE public.airline_operations SET isc_payable_to = 'WFS' WHERE airline_id = 25 AND airport_id = 51;
UPDATE public.airline_operations SET isc_payable_to = 'AGI' WHERE airline_id = 25 AND airport_id = 52;
UPDATE public.airline_operations SET isc_payable_to = 'WFS' WHERE airline_id = 25 AND airport_id = 54;
UPDATE public.airline_operations SET isc_payable_to = 'WFS' WHERE airline_id = 25 AND airport_id = 55;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport' WHERE airline_id = 25 AND airport_id = 56;
UPDATE public.airline_operations SET isc_payable_to = 'Menzies' WHERE airline_id = 25 AND airport_id = 60;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport' WHERE airline_id = 25 AND airport_id = 61;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport' WHERE airline_id = 25 AND airport_id = 65;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport' WHERE airline_id = 25 AND airport_id = 66;
UPDATE public.airline_operations SET isc_payable_to = 'WFS' WHERE airline_id = 25 AND airport_id = 67;
UPDATE public.airline_operations SET isc_payable_to = 'AGI' WHERE airline_id = 25 AND airport_id = 68;
UPDATE public.airline_operations SET isc_payable_to = 'Menzies' WHERE airline_id = 25 AND airport_id = 69;
UPDATE public.airline_operations SET isc_payable_to = 'AGI' WHERE airline_id = 25 AND airport_id = 77;
UPDATE public.airline_operations SET isc_payable_to = 'WFS' WHERE airline_id = 25 AND airport_id = 86;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport' WHERE airline_id = 25 AND airport_id = 88;
UPDATE public.airline_operations SET isc_payable_to = 'Menzies' WHERE airline_id = 25 AND airport_id = 90;
UPDATE public.airline_operations SET isc_payable_to = 'AGI' WHERE airline_id = 25 AND airport_id = 92;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport' WHERE airline_id = 25 AND airport_id = 93;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport' WHERE airline_id = 25 AND airport_id = 94;
UPDATE public.airline_operations SET isc_payable_to = 'WFS' WHERE airline_id = 25 AND airport_id = 95;
UPDATE public.airline_operations SET isc_payable_to = 'Menzies' WHERE airline_id = 25 AND airport_id = 97;
UPDATE public.airline_operations SET isc_payable_to = 'WFS' WHERE airline_id = 25 AND airport_id = 98;
UPDATE public.airline_operations SET isc_payable_to = 'Menzies' WHERE airline_id = 25 AND airport_id = 100;
UPDATE public.airline_operations SET isc_payable_to = 'AGI' WHERE airline_id = 25 AND airport_id = 101;
UPDATE public.airline_operations SET isc_payable_to = 'WFS' WHERE airline_id = 25 AND airport_id = 102;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport' WHERE airline_id = 25 AND airport_id = 103;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport' WHERE airline_id = 25 AND airport_id = 107;
UPDATE public.airline_operations SET isc_payable_to = 'AGI' WHERE airline_id = 25 AND airport_id = 111;
UPDATE public.airline_operations SET isc_payable_to = 'AGI' WHERE airline_id = 25 AND airport_id = 114;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport' WHERE airline_id = 25 AND airport_id = 121;
UPDATE public.airline_operations SET isc_payable_to = 'WFS' WHERE airline_id = 25 AND airport_id = 123;
UPDATE public.airline_operations SET isc_payable_to = 'ALLIANCE GROUND', contact_number = '973-242-0096', contact_email = 'AGIEWRSPL@ALLIANCEGROUNG.COM' WHERE airline_id = 25 AND airport_id = 126;
UPDATE public.airline_operations SET isc_payable_to = 'AGI' WHERE airline_id = 25 AND airport_id = 129;
UPDATE public.airline_operations SET isc_payable_to = 'WFS' WHERE airline_id = 25 AND airport_id = 131;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport' WHERE airline_id = 25 AND airport_id = 132;
UPDATE public.airline_operations SET isc_payable_to = 'Menzies' WHERE airline_id = 25 AND airport_id = 1169;
UPDATE public.airline_operations SET isc_payable_to = 'Menzies' WHERE airline_id = 25 AND airport_id = 1238;
UPDATE public.airline_operations SET isc_payable_to = 'AGI' WHERE airline_id = 25 AND airport_id = 1353;
UPDATE public.airline_operations SET isc_payable_to = 'Menzies' WHERE airline_id = 25 AND airport_id = 1558;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport', contact_number = '404-767-8785 ext 4 then 1', contact_email = 'ATLTKOPS@SWISSPORT.COM' WHERE airline_id = 38 AND airport_id = 1;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport', contact_number = '310-646-1917', contact_email = 'LAXTURKISH@SWISSPORT.COM' WHERE airline_id = 38 AND airport_id = 2;
UPDATE public.airline_operations SET isc_payable_to = 'ALLIANCE GROUND', contact_number = '773-686-5840', contact_email = 'tkordops@allianceground.com // mkamil@agi.aero' WHERE airline_id = 38 AND airport_id = 3;
UPDATE public.airline_operations SET isc_payable_to = 'WFS', contact_number = '972-474-1809', contact_email = 'tkdfwimport@wfs.aero' WHERE airline_id = 38 AND airport_id = 4;
UPDATE public.airline_operations SET isc_payable_to = 'WFS' WHERE airline_id = 38 AND airport_id = 5;
UPDATE public.airline_operations SET isc_payable_to = 'ALLIANCE GROUND', contact_number = '"718-553-2190 //' WHERE airline_id = 38 AND airport_id = 6;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport', contact_number = '404-767-8785 ext 4 then 1', contact_email = 'SFOTKLHOPS@SWISSPORT.COM' WHERE airline_id = 38 AND airport_id = 7;
UPDATE public.airline_operations SET isc_payable_to = 'Menzies', contact_number = '+1 206-243-6157', contact_email = 'seaimport@menziesaviation.com' WHERE airline_id = 38 AND airport_id = 8;
UPDATE public.airline_operations SET isc_payable_to = 'AGI' WHERE airline_id = 38 AND airport_id = 9;
UPDATE public.airline_operations SET isc_payable_to = 'Menzies' WHERE airline_id = 38 AND airport_id = 10;
UPDATE public.airline_operations SET isc_payable_to = 'ALLIANCE GROUND', contact_number = '(305) 871-9001 x 3 (305) 397-0161', contact_email = 'MIACARGO@THY.COM /  : turkish@nashandling.aero' WHERE airline_id = 38 AND airport_id = 11;
UPDATE public.airline_operations SET isc_payable_to = 'WFS', contact_number = '281-233-3110', contact_email = 'iahimport@wfs.aero' WHERE airline_id = 38 AND airport_id = 12;
UPDATE public.airline_operations SET isc_payable_to = 'WFS', contact_number = 'Import: 617766-3306 Export: 469629-0489', contact_email = 'BOSimportOPS@wfs.aero; bos62op@wfs.aero; boscargo@thy.com' WHERE airline_id = 38 AND airport_id = 13;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport' WHERE airline_id = 38 AND airport_id = 14;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport', contact_number = '215-365-0200', contact_email = 'PHLTKOPS@SWISSPORT.COM' WHERE airline_id = 38 AND airport_id = 16;
UPDATE public.airline_operations SET isc_payable_to = 'WFS', contact_number = '801-575-2760', contact_email = 'slcimport@wfs.aero' WHERE airline_id = 38 AND airport_id = 17;
UPDATE public.airline_operations SET isc_payable_to = 'Menzies' WHERE airline_id = 38 AND airport_id = 18;
UPDATE public.airline_operations SET isc_payable_to = 'WFS', contact_number = '800-874-8875/703.840-6400', contact_email = 'IAD.TK.OPS@CHOICE.AERO' WHERE airline_id = 38 AND airport_id = 19;
UPDATE public.airline_operations SET isc_payable_to = 'Menzies' WHERE airline_id = 38 AND airport_id = 20;
UPDATE public.airline_operations SET isc_payable_to = 'AGI' WHERE airline_id = 38 AND airport_id = 21;
UPDATE public.airline_operations SET isc_payable_to = 'Menzies' WHERE airline_id = 38 AND airport_id = 22;
UPDATE public.airline_operations SET isc_payable_to = 'Menzies' WHERE airline_id = 38 AND airport_id = 23;
UPDATE public.airline_operations SET isc_payable_to = 'AGI' WHERE airline_id = 38 AND airport_id = 24;
UPDATE public.airline_operations SET isc_payable_to = 'WFS' WHERE airline_id = 38 AND airport_id = 25;
UPDATE public.airline_operations SET isc_payable_to = 'WFS' WHERE airline_id = 38 AND airport_id = 26;
UPDATE public.airline_operations SET isc_payable_to = 'Menzies' WHERE airline_id = 38 AND airport_id = 27;
UPDATE public.airline_operations SET isc_payable_to = 'WFS', contact_number = '619-400-2200', contact_email = 'sanimport@wfs.aero' WHERE airline_id = 38 AND airport_id = 28;
UPDATE public.airline_operations SET isc_payable_to = 'AGI' WHERE airline_id = 38 AND airport_id = 29;
UPDATE public.airline_operations SET isc_payable_to = 'AGI' WHERE airline_id = 38 AND airport_id = 30;
UPDATE public.airline_operations SET isc_payable_to = 'Midwest Express', contact_number = '816-692-4033', contact_email = 'megan.moore@midwestexpressco.com Sue.Riga@midwestexpressco.com' WHERE airline_id = 38 AND airport_id = 31;
UPDATE public.airline_operations SET isc_payable_to = 'WFS' WHERE airline_id = 38 AND airport_id = 33;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport' WHERE airline_id = 38 AND airport_id = 37;
UPDATE public.airline_operations SET isc_payable_to = 'WFS' WHERE airline_id = 38 AND airport_id = 41;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport' WHERE airline_id = 38 AND airport_id = 43;
UPDATE public.airline_operations SET isc_payable_to = 'WFS', contact_number = '412-472-3300', contact_email = 'pitimport@wfs.aero' WHERE airline_id = 38 AND airport_id = 44;
UPDATE public.airline_operations SET isc_payable_to = 'Menzies' WHERE airline_id = 38 AND airport_id = 45;
UPDATE public.airline_operations SET isc_payable_to = 'AGI' WHERE airline_id = 38 AND airport_id = 47;
UPDATE public.airline_operations SET isc_payable_to = 'Menzies' WHERE airline_id = 38 AND airport_id = 49;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport' WHERE airline_id = 38 AND airport_id = 50;
UPDATE public.airline_operations SET isc_payable_to = 'WFS' WHERE airline_id = 38 AND airport_id = 51;
UPDATE public.airline_operations SET isc_payable_to = 'AGI' WHERE airline_id = 38 AND airport_id = 52;
UPDATE public.airline_operations SET isc_payable_to = 'WFS' WHERE airline_id = 38 AND airport_id = 54;
UPDATE public.airline_operations SET isc_payable_to = 'WFS' WHERE airline_id = 38 AND airport_id = 55;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport' WHERE airline_id = 38 AND airport_id = 56;
UPDATE public.airline_operations SET isc_payable_to = 'Menzies' WHERE airline_id = 38 AND airport_id = 60;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport' WHERE airline_id = 38 AND airport_id = 61;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport' WHERE airline_id = 38 AND airport_id = 65;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport' WHERE airline_id = 38 AND airport_id = 66;
UPDATE public.airline_operations SET isc_payable_to = 'WFS' WHERE airline_id = 38 AND airport_id = 67;
UPDATE public.airline_operations SET isc_payable_to = 'AGI' WHERE airline_id = 38 AND airport_id = 68;
UPDATE public.airline_operations SET isc_payable_to = 'Menzies' WHERE airline_id = 38 AND airport_id = 69;
UPDATE public.airline_operations SET isc_payable_to = 'AGI' WHERE airline_id = 38 AND airport_id = 77;
UPDATE public.airline_operations SET isc_payable_to = 'WFS' WHERE airline_id = 38 AND airport_id = 86;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport' WHERE airline_id = 38 AND airport_id = 88;
UPDATE public.airline_operations SET isc_payable_to = 'Menzies' WHERE airline_id = 38 AND airport_id = 90;
UPDATE public.airline_operations SET isc_payable_to = 'AGI' WHERE airline_id = 38 AND airport_id = 92;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport' WHERE airline_id = 38 AND airport_id = 93;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport' WHERE airline_id = 38 AND airport_id = 94;
UPDATE public.airline_operations SET isc_payable_to = 'WFS' WHERE airline_id = 38 AND airport_id = 95;
UPDATE public.airline_operations SET isc_payable_to = 'Menzies' WHERE airline_id = 38 AND airport_id = 97;
UPDATE public.airline_operations SET isc_payable_to = 'WFS' WHERE airline_id = 38 AND airport_id = 98;
UPDATE public.airline_operations SET isc_payable_to = 'Menzies' WHERE airline_id = 38 AND airport_id = 100;
UPDATE public.airline_operations SET isc_payable_to = 'AGI' WHERE airline_id = 38 AND airport_id = 101;
UPDATE public.airline_operations SET isc_payable_to = 'WFS' WHERE airline_id = 38 AND airport_id = 102;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport' WHERE airline_id = 38 AND airport_id = 103;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport' WHERE airline_id = 38 AND airport_id = 107;
UPDATE public.airline_operations SET isc_payable_to = 'AGI' WHERE airline_id = 38 AND airport_id = 111;
UPDATE public.airline_operations SET isc_payable_to = 'AGI' WHERE airline_id = 38 AND airport_id = 114;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport' WHERE airline_id = 38 AND airport_id = 121;
UPDATE public.airline_operations SET isc_payable_to = 'WFS' WHERE airline_id = 38 AND airport_id = 123;
UPDATE public.airline_operations SET isc_payable_to = 'WFS', contact_number = '973-804-2800', contact_email = 'EWRSAS@WFS.AERO' WHERE airline_id = 38 AND airport_id = 126;
UPDATE public.airline_operations SET isc_payable_to = 'AGI' WHERE airline_id = 38 AND airport_id = 129;
UPDATE public.airline_operations SET isc_payable_to = 'WFS' WHERE airline_id = 38 AND airport_id = 131;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport' WHERE airline_id = 38 AND airport_id = 132;
UPDATE public.airline_operations SET isc_payable_to = 'Menzies' WHERE airline_id = 38 AND airport_id = 1169;
UPDATE public.airline_operations SET isc_payable_to = 'Menzies' WHERE airline_id = 38 AND airport_id = 1238;
UPDATE public.airline_operations SET isc_payable_to = 'AGI' WHERE airline_id = 38 AND airport_id = 1353;
UPDATE public.airline_operations SET isc_payable_to = 'Menzies' WHERE airline_id = 38 AND airport_id = 1558;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport', contact_number = '404-767-8785', contact_email = 'ATLEKOPS@SWISSPORT.COM' WHERE airline_id = 39 AND airport_id = 1;
UPDATE public.airline_operations SET isc_payable_to = 'MERCURY AIRCARGO', contact_number = '3102586100', contact_email = 'EKIMPORT@MERCURYAIR.COM' WHERE airline_id = 39 AND airport_id = 2;
UPDATE public.airline_operations SET isc_payable_to = 'Airport Logistics /Maestro cargo', contact_number = '773-686-0700 -/- 773-570-6432', contact_email = 'ORDRES@EMIRATES.COM' WHERE airline_id = 39 AND airport_id = 3;
UPDATE public.airline_operations SET isc_payable_to = 'WFS', contact_number = '469-629-0605', contact_email = 'dfwekimport@wfs.aero' WHERE airline_id = 39 AND airport_id = 4;
UPDATE public.airline_operations SET isc_payable_to = 'WFS' WHERE airline_id = 39 AND airport_id = 5;
UPDATE public.airline_operations SET isc_payable_to = 'WFS', contact_number = '"718 656 3980--- EX-1' WHERE airline_id = 39 AND airport_id = 6;
UPDATE public.airline_operations SET isc_payable_to = 'MAC CARGO', contact_number = '(650) 737-4880', contact_email = 'sfomaccargo@maccargo.com' WHERE airline_id = 39 AND airport_id = 7;
UPDATE public.airline_operations SET isc_payable_to = 'Menzies', contact_number = '+1 206-243-6157', contact_email = 'seaimport@menziesaviation.com' WHERE airline_id = 39 AND airport_id = 8;
UPDATE public.airline_operations SET isc_payable_to = 'AGI' WHERE airline_id = 39 AND airport_id = 9;
UPDATE public.airline_operations SET isc_payable_to = 'Menzies', contact_number = '321-732-8070 * 2 * 4' WHERE airline_id = 39 AND airport_id = 10;
UPDATE public.airline_operations SET isc_payable_to = 'WFS', contact_number = '305-492-8620', contact_email = 'miawfsuae@wfs.aero' WHERE airline_id = 39 AND airport_id = 11;
UPDATE public.airline_operations SET isc_payable_to = 'WFS', contact_number = '281-233-3110', contact_email = 'iahimport@wfs.aero' WHERE airline_id = 39 AND airport_id = 12;
UPDATE public.airline_operations SET isc_payable_to = 'WFS', contact_number = '617-702-2848' WHERE airline_id = 39 AND airport_id = 13;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport' WHERE airline_id = 39 AND airport_id = 14;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport', contact_number = '215-365-0200', contact_email = 'PHLEKOPS@SWISSPORT.COM' WHERE airline_id = 39 AND airport_id = 16;
UPDATE public.airline_operations SET isc_payable_to = 'WFS', contact_number = '801-575-2760', contact_email = 'slcimport@wfs.aero' WHERE airline_id = 39 AND airport_id = 17;
UPDATE public.airline_operations SET isc_payable_to = 'Menzies' WHERE airline_id = 39 AND airport_id = 18;
UPDATE public.airline_operations SET isc_payable_to = 'WFS', contact_number = '703-840-8392', contact_email = 'IAD RES <iadres@emirates.com>; IADMGR <iadmgr@casusa.com>; Mahmoud Reda.Saad <MSaad@wfs.aero>; Nadia Elmana <Nadia.Elmana@wfs.aero>' WHERE airline_id = 39 AND airport_id = 19;
UPDATE public.airline_operations SET isc_payable_to = 'Air General' WHERE airline_id = 39 AND airport_id = 20;
UPDATE public.airline_operations SET isc_payable_to = 'Menzies' WHERE airline_id = 39 AND airport_id = 21;
UPDATE public.airline_operations SET isc_payable_to = 'Menzies' WHERE airline_id = 39 AND airport_id = 22;
UPDATE public.airline_operations SET isc_payable_to = 'Menzies' WHERE airline_id = 39 AND airport_id = 23;
UPDATE public.airline_operations SET isc_payable_to = 'AGI' WHERE airline_id = 39 AND airport_id = 24;
UPDATE public.airline_operations SET isc_payable_to = 'WFS' WHERE airline_id = 39 AND airport_id = 25;
UPDATE public.airline_operations SET isc_payable_to = 'WFS' WHERE airline_id = 39 AND airport_id = 26;
UPDATE public.airline_operations SET isc_payable_to = 'Menzies' WHERE airline_id = 39 AND airport_id = 27;
UPDATE public.airline_operations SET isc_payable_to = 'WFS', contact_number = '619-400-2200', contact_email = 'sanimport@wfs.aero' WHERE airline_id = 39 AND airport_id = 28;
UPDATE public.airline_operations SET isc_payable_to = 'AGI' WHERE airline_id = 39 AND airport_id = 29;
UPDATE public.airline_operations SET isc_payable_to = 'AGI' WHERE airline_id = 39 AND airport_id = 30;
UPDATE public.airline_operations SET isc_payable_to = 'WFS' WHERE airline_id = 39 AND airport_id = 33;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport' WHERE airline_id = 39 AND airport_id = 37;
UPDATE public.airline_operations SET isc_payable_to = 'WFS' WHERE airline_id = 39 AND airport_id = 41;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport' WHERE airline_id = 39 AND airport_id = 43;
UPDATE public.airline_operations SET isc_payable_to = 'WFS', contact_number = '412-472-3300', contact_email = 'pitimport@wfs.aero' WHERE airline_id = 39 AND airport_id = 44;
UPDATE public.airline_operations SET isc_payable_to = 'Menzies' WHERE airline_id = 39 AND airport_id = 45;
UPDATE public.airline_operations SET isc_payable_to = 'AGI' WHERE airline_id = 39 AND airport_id = 47;
UPDATE public.airline_operations SET isc_payable_to = 'Menzies' WHERE airline_id = 39 AND airport_id = 49;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport' WHERE airline_id = 39 AND airport_id = 50;
UPDATE public.airline_operations SET isc_payable_to = 'WFS' WHERE airline_id = 39 AND airport_id = 51;
UPDATE public.airline_operations SET isc_payable_to = 'AGI' WHERE airline_id = 39 AND airport_id = 52;
UPDATE public.airline_operations SET isc_payable_to = 'WFS' WHERE airline_id = 39 AND airport_id = 54;
UPDATE public.airline_operations SET isc_payable_to = 'WFS' WHERE airline_id = 39 AND airport_id = 55;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport' WHERE airline_id = 39 AND airport_id = 56;
UPDATE public.airline_operations SET isc_payable_to = 'Menzies' WHERE airline_id = 39 AND airport_id = 60;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport' WHERE airline_id = 39 AND airport_id = 61;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport' WHERE airline_id = 39 AND airport_id = 65;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport' WHERE airline_id = 39 AND airport_id = 66;
UPDATE public.airline_operations SET isc_payable_to = 'WFS' WHERE airline_id = 39 AND airport_id = 67;
UPDATE public.airline_operations SET isc_payable_to = 'AGI' WHERE airline_id = 39 AND airport_id = 68;
UPDATE public.airline_operations SET isc_payable_to = 'Menzies' WHERE airline_id = 39 AND airport_id = 69;
UPDATE public.airline_operations SET isc_payable_to = 'AGI' WHERE airline_id = 39 AND airport_id = 77;
UPDATE public.airline_operations SET isc_payable_to = 'WFS' WHERE airline_id = 39 AND airport_id = 86;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport' WHERE airline_id = 39 AND airport_id = 88;
UPDATE public.airline_operations SET isc_payable_to = 'Menzies' WHERE airline_id = 39 AND airport_id = 90;
UPDATE public.airline_operations SET isc_payable_to = 'AGI' WHERE airline_id = 39 AND airport_id = 92;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport' WHERE airline_id = 39 AND airport_id = 93;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport' WHERE airline_id = 39 AND airport_id = 94;
UPDATE public.airline_operations SET isc_payable_to = 'WFS' WHERE airline_id = 39 AND airport_id = 95;
UPDATE public.airline_operations SET isc_payable_to = 'Menzies' WHERE airline_id = 39 AND airport_id = 97;
UPDATE public.airline_operations SET isc_payable_to = 'WFS' WHERE airline_id = 39 AND airport_id = 98;
UPDATE public.airline_operations SET isc_payable_to = 'Menzies' WHERE airline_id = 39 AND airport_id = 100;
UPDATE public.airline_operations SET isc_payable_to = 'AGI' WHERE airline_id = 39 AND airport_id = 101;
UPDATE public.airline_operations SET isc_payable_to = 'WFS' WHERE airline_id = 39 AND airport_id = 102;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport' WHERE airline_id = 39 AND airport_id = 103;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport' WHERE airline_id = 39 AND airport_id = 107;
UPDATE public.airline_operations SET isc_payable_to = 'AGI' WHERE airline_id = 39 AND airport_id = 111;
UPDATE public.airline_operations SET isc_payable_to = 'AGI' WHERE airline_id = 39 AND airport_id = 114;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport' WHERE airline_id = 39 AND airport_id = 121;
UPDATE public.airline_operations SET isc_payable_to = 'WFS' WHERE airline_id = 39 AND airport_id = 123;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport', contact_number = '973-206-0660', contact_email = 'AGIEKEWR@ALLIANCEGROUND.COM' WHERE airline_id = 39 AND airport_id = 126;
UPDATE public.airline_operations SET isc_payable_to = 'AGI' WHERE airline_id = 39 AND airport_id = 129;
UPDATE public.airline_operations SET isc_payable_to = 'WFS' WHERE airline_id = 39 AND airport_id = 131;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport' WHERE airline_id = 39 AND airport_id = 132;
UPDATE public.airline_operations SET isc_payable_to = 'Menzies' WHERE airline_id = 39 AND airport_id = 1169;
UPDATE public.airline_operations SET isc_payable_to = 'Menzies' WHERE airline_id = 39 AND airport_id = 1238;
UPDATE public.airline_operations SET isc_payable_to = 'AGI' WHERE airline_id = 39 AND airport_id = 1353;
UPDATE public.airline_operations SET isc_payable_to = 'Menzies' WHERE airline_id = 39 AND airport_id = 1558;
UPDATE public.airline_operations SET isc_payable_to = 'SWISSPORT', contact_number = '404-767-8785 ext 4 then  1', contact_email = 'ATLQROPS@SWISSPORT.COM' WHERE airline_id = 40 AND airport_id = 1;
UPDATE public.airline_operations SET isc_payable_to = 'WFS', contact_number = '310-988-7260 /  310 258 6116', contact_email = 'qrlaximport@wfs.aero' WHERE airline_id = 40 AND airport_id = 2;
UPDATE public.airline_operations SET isc_payable_to = 'ALLIANCEGROUND', contact_number = '(773) 683-3940 x5', contact_email = 'QRORDIMP@ALLIANCEGROUND.COM' WHERE airline_id = 40 AND airport_id = 3;
UPDATE public.airline_operations SET isc_payable_to = 'Pinnacle Logistics', contact_number = '972-586-2880', contact_email = 'DFWCARGO@US.QATARAIRWAYS.COM // PVAKAUTA@PINNACLELOGISTICS.COM // QRDFW@pinnaclelogistics.com // hstump@us.qatarairways.com' WHERE airline_id = 40 AND airport_id = 4;
UPDATE public.airline_operations SET isc_payable_to = 'WFS' WHERE airline_id = 40 AND airport_id = 5;
UPDATE public.airline_operations SET isc_payable_to = 'WFS', contact_number = '"718 244 5250', contact_email = '718 521 4174",jfkcargoops@qatarairways.comJFKCARGO@US.QATARAIRWAYS.COM // qrjfkimport@wfs.aero' WHERE airline_id = 40 AND airport_id = 6;
UPDATE public.airline_operations SET isc_payable_to = 'MENZIESAVIATION', contact_number = '650-826-5400 x 5 x 1', contact_email = 'sfo.qr@menziesaviation.com' WHERE airline_id = 40 AND airport_id = 7;
UPDATE public.airline_operations SET isc_payable_to = 'Menzies', contact_number = '+1 206-243-6157', contact_email = 'seaimport@menziesaviation.com' WHERE airline_id = 40 AND airport_id = 8;
UPDATE public.airline_operations SET isc_payable_to = 'AGI' WHERE airline_id = 40 AND airport_id = 9;
UPDATE public.airline_operations SET isc_payable_to = 'Menzies' WHERE airline_id = 40 AND airport_id = 10;
UPDATE public.airline_operations SET isc_payable_to = 'LATAM', contact_number = '(305) 874-2700', contact_email = 'COUNTERIMPORT@LATAM.COM' WHERE airline_id = 40 AND airport_id = 11;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport', contact_number = '832-827-5830', contact_email = 'QRIAHIMP@SWISSPORT.COM' WHERE airline_id = 40 AND airport_id = 12;
UPDATE public.airline_operations SET isc_payable_to = 'QASLLC', contact_number = '617-567-0322', contact_email = 'QATARBOSCARGO@QASLLC.AERO' WHERE airline_id = 40 AND airport_id = 13;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport' WHERE airline_id = 40 AND airport_id = 14;
UPDATE public.airline_operations SET isc_payable_to = 'WFS', contact_number = '215-365-7100', contact_email = 'qrphlimport@wfs.aero' WHERE airline_id = 40 AND airport_id = 16;
UPDATE public.airline_operations SET isc_payable_to = 'WFS', contact_number = '801-575-2760', contact_email = 'slcimport@wfs.aero' WHERE airline_id = 40 AND airport_id = 17;
UPDATE public.airline_operations SET isc_payable_to = 'Menzies' WHERE airline_id = 40 AND airport_id = 18;
UPDATE public.airline_operations SET isc_payable_to = 'WFS', contact_number = '+1 703-572-7530' WHERE airline_id = 40 AND airport_id = 19;
UPDATE public.airline_operations SET isc_payable_to = 'Menzies' WHERE airline_id = 40 AND airport_id = 20;
UPDATE public.airline_operations SET isc_payable_to = 'AGI' WHERE airline_id = 40 AND airport_id = 21;
UPDATE public.airline_operations SET isc_payable_to = 'Menzies' WHERE airline_id = 40 AND airport_id = 22;
UPDATE public.airline_operations SET isc_payable_to = 'Menzies' WHERE airline_id = 40 AND airport_id = 23;
UPDATE public.airline_operations SET isc_payable_to = 'AGI' WHERE airline_id = 40 AND airport_id = 24;
UPDATE public.airline_operations SET isc_payable_to = 'WFS' WHERE airline_id = 40 AND airport_id = 25;
UPDATE public.airline_operations SET isc_payable_to = 'WFS' WHERE airline_id = 40 AND airport_id = 26;
UPDATE public.airline_operations SET isc_payable_to = 'Menzies' WHERE airline_id = 40 AND airport_id = 27;
UPDATE public.airline_operations SET isc_payable_to = 'WFS', contact_number = '619-400-2200', contact_email = 'sanimport@wfs.aero' WHERE airline_id = 40 AND airport_id = 28;
UPDATE public.airline_operations SET isc_payable_to = 'AGI' WHERE airline_id = 40 AND airport_id = 29;
UPDATE public.airline_operations SET isc_payable_to = 'AGI' WHERE airline_id = 40 AND airport_id = 30;
UPDATE public.airline_operations SET isc_payable_to = 'LKTRANSPORTLLC', contact_email = '"mci_imports@forwardair.com' WHERE airline_id = 40 AND airport_id = 31;
UPDATE public.airline_operations SET isc_payable_to = 'WFS' WHERE airline_id = 40 AND airport_id = 33;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport' WHERE airline_id = 40 AND airport_id = 37;
UPDATE public.airline_operations SET isc_payable_to = 'WFS' WHERE airline_id = 40 AND airport_id = 41;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport' WHERE airline_id = 40 AND airport_id = 43;
UPDATE public.airline_operations SET isc_payable_to = 'WFS', contact_number = '412-472-3300', contact_email = 'pitqrimport@wfs.aero' WHERE airline_id = 40 AND airport_id = 44;
UPDATE public.airline_operations SET isc_payable_to = 'Menzies' WHERE airline_id = 40 AND airport_id = 45;
UPDATE public.airline_operations SET isc_payable_to = 'AGI' WHERE airline_id = 40 AND airport_id = 47;
UPDATE public.airline_operations SET isc_payable_to = 'Menzies' WHERE airline_id = 40 AND airport_id = 49;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport' WHERE airline_id = 40 AND airport_id = 50;
UPDATE public.airline_operations SET isc_payable_to = 'WFS' WHERE airline_id = 40 AND airport_id = 51;
UPDATE public.airline_operations SET isc_payable_to = 'AGI' WHERE airline_id = 40 AND airport_id = 52;
UPDATE public.airline_operations SET isc_payable_to = 'WFS' WHERE airline_id = 40 AND airport_id = 54;
UPDATE public.airline_operations SET isc_payable_to = 'WFS' WHERE airline_id = 40 AND airport_id = 55;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport' WHERE airline_id = 40 AND airport_id = 56;
UPDATE public.airline_operations SET isc_payable_to = 'Menzies' WHERE airline_id = 40 AND airport_id = 60;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport' WHERE airline_id = 40 AND airport_id = 61;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport' WHERE airline_id = 40 AND airport_id = 65;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport' WHERE airline_id = 40 AND airport_id = 66;
UPDATE public.airline_operations SET isc_payable_to = 'WFS' WHERE airline_id = 40 AND airport_id = 67;
UPDATE public.airline_operations SET isc_payable_to = 'AGI' WHERE airline_id = 40 AND airport_id = 68;
UPDATE public.airline_operations SET isc_payable_to = 'Menzies' WHERE airline_id = 40 AND airport_id = 69;
UPDATE public.airline_operations SET isc_payable_to = 'AGI' WHERE airline_id = 40 AND airport_id = 77;
UPDATE public.airline_operations SET isc_payable_to = 'WFS' WHERE airline_id = 40 AND airport_id = 86;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport' WHERE airline_id = 40 AND airport_id = 88;
UPDATE public.airline_operations SET isc_payable_to = 'Menzies' WHERE airline_id = 40 AND airport_id = 90;
UPDATE public.airline_operations SET isc_payable_to = 'AGI' WHERE airline_id = 40 AND airport_id = 92;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport' WHERE airline_id = 40 AND airport_id = 93;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport' WHERE airline_id = 40 AND airport_id = 94;
UPDATE public.airline_operations SET isc_payable_to = 'WFS' WHERE airline_id = 40 AND airport_id = 95;
UPDATE public.airline_operations SET isc_payable_to = 'Menzies' WHERE airline_id = 40 AND airport_id = 97;
UPDATE public.airline_operations SET isc_payable_to = 'WFS' WHERE airline_id = 40 AND airport_id = 98;
UPDATE public.airline_operations SET isc_payable_to = 'Menzies' WHERE airline_id = 40 AND airport_id = 100;
UPDATE public.airline_operations SET isc_payable_to = 'AGI' WHERE airline_id = 40 AND airport_id = 101;
UPDATE public.airline_operations SET isc_payable_to = 'WFS' WHERE airline_id = 40 AND airport_id = 102;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport' WHERE airline_id = 40 AND airport_id = 103;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport' WHERE airline_id = 40 AND airport_id = 107;
UPDATE public.airline_operations SET isc_payable_to = 'AGI' WHERE airline_id = 40 AND airport_id = 111;
UPDATE public.airline_operations SET isc_payable_to = 'AGI' WHERE airline_id = 40 AND airport_id = 114;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport' WHERE airline_id = 40 AND airport_id = 121;
UPDATE public.airline_operations SET isc_payable_to = 'WFS' WHERE airline_id = 40 AND airport_id = 123;
UPDATE public.airline_operations SET isc_payable_to = 'FORWARDAIR', contact_number = '(973) 690-5767', contact_email = 'fa_ewr@forwardair.com' WHERE airline_id = 40 AND airport_id = 126;
UPDATE public.airline_operations SET isc_payable_to = 'AGI' WHERE airline_id = 40 AND airport_id = 129;
UPDATE public.airline_operations SET isc_payable_to = 'WFS' WHERE airline_id = 40 AND airport_id = 131;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport' WHERE airline_id = 40 AND airport_id = 132;
UPDATE public.airline_operations SET isc_payable_to = 'Menzies' WHERE airline_id = 40 AND airport_id = 1169;
UPDATE public.airline_operations SET isc_payable_to = 'Menzies' WHERE airline_id = 40 AND airport_id = 1238;
UPDATE public.airline_operations SET isc_payable_to = 'AGI' WHERE airline_id = 40 AND airport_id = 1353;
UPDATE public.airline_operations SET isc_payable_to = 'Menzies' WHERE airline_id = 40 AND airport_id = 1558;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport', contact_number = '404-767-8785' WHERE airline_id = 226 AND airport_id = 1;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport', contact_number = '310-417-9126', contact_email = 'LAX5YOPS@SWISSPORT.COM' WHERE airline_id = 226 AND airport_id = 2;
UPDATE public.airline_operations SET isc_payable_to = 'WFS', contact_number = '+1 773-888-7252', contact_email = 'ordimport@wfs.aero' WHERE airline_id = 226 AND airport_id = 3;
UPDATE public.airline_operations SET isc_payable_to = 'Menzies' WHERE airline_id = 226 AND airport_id = 4;
UPDATE public.airline_operations SET isc_payable_to = 'WFS' WHERE airline_id = 226 AND airport_id = 5;
UPDATE public.airline_operations SET isc_payable_to = 'WFS', contact_number = '"718-880-3554' WHERE airline_id = 226 AND airport_id = 6;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport' WHERE airline_id = 226 AND airport_id = 7;
UPDATE public.airline_operations SET isc_payable_to = 'Menzies', contact_number = '+1 206-243-6157', contact_email = 'seaimport@menziesaviation.com' WHERE airline_id = 226 AND airport_id = 8;
UPDATE public.airline_operations SET isc_payable_to = 'AGI' WHERE airline_id = 226 AND airport_id = 9;
UPDATE public.airline_operations SET isc_payable_to = 'Menzies' WHERE airline_id = 226 AND airport_id = 10;
UPDATE public.airline_operations SET isc_payable_to = 'wfs', contact_number = '305-777-7295', contact_email = 'miaimport@wfs.aero' WHERE airline_id = 226 AND airport_id = 11;
UPDATE public.airline_operations SET isc_payable_to = 'WFS', contact_number = '281-233-3110', contact_email = '5yiahimport@wfs.aero' WHERE airline_id = 226 AND airport_id = 12;
UPDATE public.airline_operations SET isc_payable_to = 'AGI' WHERE airline_id = 226 AND airport_id = 13;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport' WHERE airline_id = 226 AND airport_id = 14;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport', contact_number = '215-365-0200', contact_email = 'PHL5YOPS@SWISSPORT.COM' WHERE airline_id = 226 AND airport_id = 16;
UPDATE public.airline_operations SET isc_payable_to = 'WFS', contact_number = '801-575-2760', contact_email = 'slcimport@wfs.aero' WHERE airline_id = 226 AND airport_id = 17;
UPDATE public.airline_operations SET isc_payable_to = 'Menzies' WHERE airline_id = 226 AND airport_id = 18;
UPDATE public.airline_operations SET isc_payable_to = 'WFS', contact_number = '+1 703-572-7530' WHERE airline_id = 226 AND airport_id = 19;
UPDATE public.airline_operations SET isc_payable_to = 'Menzies' WHERE airline_id = 226 AND airport_id = 20;
UPDATE public.airline_operations SET isc_payable_to = 'AGI' WHERE airline_id = 226 AND airport_id = 21;
UPDATE public.airline_operations SET isc_payable_to = 'Menzies' WHERE airline_id = 226 AND airport_id = 22;
UPDATE public.airline_operations SET isc_payable_to = 'Menzies' WHERE airline_id = 226 AND airport_id = 23;
UPDATE public.airline_operations SET isc_payable_to = 'AGI' WHERE airline_id = 226 AND airport_id = 24;
UPDATE public.airline_operations SET isc_payable_to = 'WFS' WHERE airline_id = 226 AND airport_id = 25;
UPDATE public.airline_operations SET isc_payable_to = 'WFS' WHERE airline_id = 226 AND airport_id = 26;
UPDATE public.airline_operations SET isc_payable_to = 'Menzies' WHERE airline_id = 226 AND airport_id = 27;
UPDATE public.airline_operations SET isc_payable_to = 'WFS', contact_number = '619-400-2200', contact_email = 'sanimport@wfs.aero' WHERE airline_id = 226 AND airport_id = 28;
UPDATE public.airline_operations SET isc_payable_to = 'AGI' WHERE airline_id = 226 AND airport_id = 29;
UPDATE public.airline_operations SET isc_payable_to = 'AGI' WHERE airline_id = 226 AND airport_id = 30;
UPDATE public.airline_operations SET isc_payable_to = 'WFS' WHERE airline_id = 226 AND airport_id = 33;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport' WHERE airline_id = 226 AND airport_id = 37;
UPDATE public.airline_operations SET isc_payable_to = 'WFS' WHERE airline_id = 226 AND airport_id = 41;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport' WHERE airline_id = 226 AND airport_id = 43;
UPDATE public.airline_operations SET isc_payable_to = 'WFS', contact_number = '412-472-3300', contact_email = 'pitimport@wfs.aero' WHERE airline_id = 226 AND airport_id = 44;
UPDATE public.airline_operations SET isc_payable_to = 'Menzies' WHERE airline_id = 226 AND airport_id = 45;
UPDATE public.airline_operations SET isc_payable_to = 'AGI' WHERE airline_id = 226 AND airport_id = 47;
UPDATE public.airline_operations SET isc_payable_to = 'Menzies' WHERE airline_id = 226 AND airport_id = 49;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport' WHERE airline_id = 226 AND airport_id = 50;
UPDATE public.airline_operations SET isc_payable_to = 'WFS' WHERE airline_id = 226 AND airport_id = 51;
UPDATE public.airline_operations SET isc_payable_to = 'AGI' WHERE airline_id = 226 AND airport_id = 52;
UPDATE public.airline_operations SET isc_payable_to = 'WFS' WHERE airline_id = 226 AND airport_id = 54;
UPDATE public.airline_operations SET isc_payable_to = 'WFS' WHERE airline_id = 226 AND airport_id = 55;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport' WHERE airline_id = 226 AND airport_id = 56;
UPDATE public.airline_operations SET isc_payable_to = 'Menzies' WHERE airline_id = 226 AND airport_id = 60;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport' WHERE airline_id = 226 AND airport_id = 61;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport' WHERE airline_id = 226 AND airport_id = 65;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport' WHERE airline_id = 226 AND airport_id = 66;
UPDATE public.airline_operations SET isc_payable_to = 'WFS' WHERE airline_id = 226 AND airport_id = 67;
UPDATE public.airline_operations SET isc_payable_to = 'AGI' WHERE airline_id = 226 AND airport_id = 68;
UPDATE public.airline_operations SET isc_payable_to = 'Menzies' WHERE airline_id = 226 AND airport_id = 69;
UPDATE public.airline_operations SET isc_payable_to = 'AGI' WHERE airline_id = 226 AND airport_id = 77;
UPDATE public.airline_operations SET isc_payable_to = 'WFS' WHERE airline_id = 226 AND airport_id = 86;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport' WHERE airline_id = 226 AND airport_id = 88;
UPDATE public.airline_operations SET isc_payable_to = 'Menzies' WHERE airline_id = 226 AND airport_id = 90;
UPDATE public.airline_operations SET isc_payable_to = 'AGI' WHERE airline_id = 226 AND airport_id = 92;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport' WHERE airline_id = 226 AND airport_id = 93;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport' WHERE airline_id = 226 AND airport_id = 94;
UPDATE public.airline_operations SET isc_payable_to = 'WFS' WHERE airline_id = 226 AND airport_id = 95;
UPDATE public.airline_operations SET isc_payable_to = 'Menzies' WHERE airline_id = 226 AND airport_id = 97;
UPDATE public.airline_operations SET isc_payable_to = 'WFS' WHERE airline_id = 226 AND airport_id = 98;
UPDATE public.airline_operations SET isc_payable_to = 'Menzies' WHERE airline_id = 226 AND airport_id = 100;
UPDATE public.airline_operations SET isc_payable_to = 'AGI' WHERE airline_id = 226 AND airport_id = 101;
UPDATE public.airline_operations SET isc_payable_to = 'WFS' WHERE airline_id = 226 AND airport_id = 102;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport' WHERE airline_id = 226 AND airport_id = 103;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport' WHERE airline_id = 226 AND airport_id = 107;
UPDATE public.airline_operations SET isc_payable_to = 'AGI' WHERE airline_id = 226 AND airport_id = 111;
UPDATE public.airline_operations SET isc_payable_to = 'AGI' WHERE airline_id = 226 AND airport_id = 114;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport' WHERE airline_id = 226 AND airport_id = 121;
UPDATE public.airline_operations SET isc_payable_to = 'WFS' WHERE airline_id = 226 AND airport_id = 123;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport', contact_number = '973-681-3376', contact_email = 'ewrekops@swissport.com' WHERE airline_id = 226 AND airport_id = 126;
UPDATE public.airline_operations SET isc_payable_to = 'AGI' WHERE airline_id = 226 AND airport_id = 129;
UPDATE public.airline_operations SET isc_payable_to = 'WFS' WHERE airline_id = 226 AND airport_id = 131;
UPDATE public.airline_operations SET isc_payable_to = 'Swissport' WHERE airline_id = 226 AND airport_id = 132;
UPDATE public.airline_operations SET isc_payable_to = 'Menzies' WHERE airline_id = 226 AND airport_id = 1169;
UPDATE public.airline_operations SET isc_payable_to = 'Menzies' WHERE airline_id = 226 AND airport_id = 1238;
UPDATE public.airline_operations SET isc_payable_to = 'AGI' WHERE airline_id = 226 AND airport_id = 1353;
UPDATE public.airline_operations SET isc_payable_to = 'Menzies' WHERE airline_id = 226 AND airport_id = 1558;
