// Comprehensive US airport data from airportcodes.us and CBP sources
const US_AIRPORTS_DATA = [
  // Major International Hubs
  { name: "Hartsfield-Jackson Atlanta International Airport", iataCode: "ATL", cbpPortCode: "0101", city: "Atlanta", state: "GA", country: "US", customsApproved: true },
  { name: "Los Angeles International Airport", iataCode: "LAX", cbpPortCode: "2801", city: "Los Angeles", state: "CA", country: "US", customsApproved: true },
  { name: "O'Hare International Airport", iataCode: "ORD", cbpPortCode: "3901", city: "Chicago", state: "IL", country: "US", customsApproved: true },
  { name: "Dallas/Fort Worth International Airport", iataCode: "DFW", cbpPortCode: "5501", city: "Dallas", state: "TX", country: "US", customsApproved: true },
  { name: "Denver International Airport", iataCode: "DEN", cbpPortCode: "5904", city: "Denver", state: "CO", country: "US", customsApproved: true },
  { name: "John F. Kennedy International Airport", iataCode: "JFK", cbpPortCode: "4701", city: "New York", state: "NY", country: "US", customsApproved: true },
  { name: "San Francisco International Airport", iataCode: "SFO", cbpPortCode: "2801", city: "San Francisco", state: "CA", country: "US", customsApproved: true },
  { name: "Seattle-Tacoma International Airport", iataCode: "SEA", cbpPortCode: "3001", city: "Seattle", state: "WA", country: "US", customsApproved: true },
  { name: "McCarran International Airport", iataCode: "LAS", cbpPortCode: "2901", city: "Las Vegas", state: "NV", country: "US", customsApproved: true },
  { name: "Orlando International Airport", iataCode: "MCO", cbpPortCode: "0901", city: "Orlando", state: "FL", country: "US", customsApproved: true },
  { name: "Miami International Airport", iataCode: "MIA", cbpPortCode: "5201", city: "Miami", state: "FL", country: "US", customsApproved: true },
  { name: "George Bush Intercontinental Airport", iataCode: "IAH", cbpPortCode: "5301", city: "Houston", state: "TX", country: "US", customsApproved: true },
  { name: "Boston Logan International Airport", iataCode: "BOS", cbpPortCode: "0401", city: "Boston", state: "MA", country: "US", customsApproved: true },
  { name: "Minneapolis-Saint Paul International Airport", iataCode: "MSP", cbpPortCode: "3401", city: "Minneapolis", state: "MN", country: "US", customsApproved: true },
  { name: "Detroit Metropolitan Wayne County Airport", iataCode: "DTW", cbpPortCode: "3801", city: "Detroit", state: "MI", country: "US", customsApproved: true },
  { name: "Philadelphia International Airport", iataCode: "PHL", cbpPortCode: "4701", city: "Philadelphia", state: "PA", country: "US", customsApproved: true },
  { name: "Salt Lake City International Airport", iataCode: "SLC", cbpPortCode: "2901", city: "Salt Lake City", state: "UT", country: "US", customsApproved: true },
  { name: "Ronald Reagan Washington National Airport", iataCode: "DCA", cbpPortCode: "1102", city: "Arlington", state: "VA", country: "US", customsApproved: false },
  { name: "Washington Dulles International Airport", iataCode: "IAD", cbpPortCode: "1102", city: "Dulles", state: "VA", country: "US", customsApproved: true },
  { name: "Charlotte Douglas International Airport", iataCode: "CLT", cbpPortCode: "4801", city: "Charlotte", state: "NC", country: "US", customsApproved: true },
  { name: "Fort Lauderdale-Hollywood International Airport", iataCode: "FLL", cbpPortCode: "5204", city: "Fort Lauderdale", state: "FL", country: "US", customsApproved: true },
  { name: "Phoenix Sky Harbor International Airport", iataCode: "PHX", cbpPortCode: "2601", city: "Phoenix", state: "AZ", country: "US", customsApproved: true },
  { name: "Portland International Airport", iataCode: "PDX", cbpPortCode: "2901", city: "Portland", state: "OR", country: "US", customsApproved: true },
  { name: "Baltimore/Washington International Airport", iataCode: "BWI", cbpPortCode: "1301", city: "Baltimore", state: "MD", country: "US", customsApproved: true },
  { name: "Nashville International Airport", iataCode: "BNA", cbpPortCode: "4801", city: "Nashville", state: "TN", country: "US", customsApproved: true },
  { name: "Austin-Bergstrom International Airport", iataCode: "AUS", cbpPortCode: "5507", city: "Austin", state: "TX", country: "US", customsApproved: true },
  { name: "Dallas Love Field", iataCode: "DAL", cbpPortCode: "5501", city: "Dallas", state: "TX", country: "US", customsApproved: false },
  { name: "San Diego International Airport", iataCode: "SAN", cbpPortCode: "2501", city: "San Diego", state: "CA", country: "US", customsApproved: true },
  { name: "Tampa International Airport", iataCode: "TPA", cbpPortCode: "0903", city: "Tampa", state: "FL", country: "US", customsApproved: true },
  { name: "St. Louis Lambert International Airport", iataCode: "STL", cbpPortCode: "4501", city: "St. Louis", state: "MO", country: "US", customsApproved: true },
  { name: "Kansas City International Airport", iataCode: "MCI", cbpPortCode: "4501", city: "Kansas City", state: "MO", country: "US", customsApproved: true },
  { name: "Midway International Airport", iataCode: "MDW", cbpPortCode: "3901", city: "Chicago", state: "IL", country: "US", customsApproved: false },
  { name: "Honolulu International Airport", iataCode: "HNL", cbpPortCode: "3101", city: "Honolulu", state: "HI", country: "US", customsApproved: true },
  { name: "Kahului Airport", iataCode: "OGG", cbpPortCode: "3101", city: "Kahului", state: "HI", country: "US", customsApproved: true },
  { name: "Lihue Airport", iataCode: "LIH", cbpPortCode: "3101", city: "Lihue", state: "HI", country: "US", customsApproved: false },
  { name: "Kona International Airport", iataCode: "KOA", cbpPortCode: "3101", city: "Kailua-Kona", state: "HI", country: "US", customsApproved: false },
  { name: "Ted Stevens Anchorage International Airport", iataCode: "ANC", cbpPortCode: "3201", city: "Anchorage", state: "AK", country: "US", customsApproved: true },
  { name: "Fairbanks International Airport", iataCode: "FAI", cbpPortCode: "3201", city: "Fairbanks", state: "AK", country: "US", customsApproved: false },
  { name: "Juneau International Airport", iataCode: "JNU", cbpPortCode: "3201", city: "Juneau", state: "AK", country: "US", customsApproved: false },
  { name: "New Orleans Louis Armstrong International Airport", iataCode: "MSY", cbpPortCode: "2001", city: "New Orleans", state: "LA", country: "US", customsApproved: true },
  { name: "Indianapolis International Airport", iataCode: "IND", cbpPortCode: "3701", city: "Indianapolis", state: "IN", country: "US", customsApproved: true },
  { name: "Columbus John Glenn International Airport", iataCode: "CMH", cbpPortCode: "4101", city: "Columbus", state: "OH", country: "US", customsApproved: true },
  { name: "Cleveland Hopkins International Airport", iataCode: "CLE", cbpPortCode: "4101", city: "Cleveland", state: "OH", country: "US", customsApproved: true },
  { name: "Pittsburgh International Airport", iataCode: "PIT", cbpPortCode: "4701", city: "Pittsburgh", state: "PA", country: "US", customsApproved: true },
  { name: "Louisville Muhammad Ali International Airport", iataCode: "SDF", cbpPortCode: "1901", city: "Louisville", state: "KY", country: "US", customsApproved: true },
  { name: "Richmond International Airport", iataCode: "RIC", cbpPortCode: "1103", city: "Richmond", state: "VA", country: "US", customsApproved: false },
  { name: "Raleigh-Durham International Airport", iataCode: "RDU", cbpPortCode: "4801", city: "Raleigh", state: "NC", country: "US", customsApproved: true },
  { name: "Jacksonville International Airport", iataCode: "JAX", cbpPortCode: "0902", city: "Jacksonville", state: "FL", country: "US", customsApproved: true },
  { name: "Palm Beach International Airport", iataCode: "PBI", cbpPortCode: "5203", city: "West Palm Beach", state: "FL", country: "US", customsApproved: true },
  { name: "Sarasota Bradenton International Airport", iataCode: "SRQ", cbpPortCode: "0903", city: "Sarasota", state: "FL", country: "US", customsApproved: false },
  { name: "Southwest Florida International Airport", iataCode: "RSW", cbpPortCode: "0904", city: "Fort Myers", state: "FL", country: "US", customsApproved: true },
  { name: "Pensacola International Airport", iataCode: "PNS", cbpPortCode: "0906", city: "Pensacola", state: "FL", country: "US", customsApproved: false },
  { name: "Daytona Beach International Airport", iataCode: "DAB", cbpPortCode: "0905", city: "Daytona Beach", state: "FL", country: "US", customsApproved: false },
  { name: "Memphis International Airport", iataCode: "MEM", cbpPortCode: "4801", city: "Memphis", state: "TN", country: "US", customsApproved: true },
  { name: "El Paso International Airport", iataCode: "ELP", cbpPortCode: "2401", city: "El Paso", state: "TX", country: "US", customsApproved: true },
  { name: "San Antonio International Airport", iataCode: "SAT", cbpPortCode: "5507", city: "San Antonio", state: "TX", country: "US", customsApproved: true },
  { name: "Corpus Christi International Airport", iataCode: "CRP", cbpPortCode: "5501", city: "Corpus Christi", state: "TX", country: "US", customsApproved: false },
  { name: "Lubbock Preston Smith International Airport", iataCode: "LBB", cbpPortCode: "5502", city: "Lubbock", state: "TX", country: "US", customsApproved: false },
  { name: "Amarillo Rick Husband International Airport", iataCode: "AMA", cbpPortCode: "5503", city: "Amarillo", state: "TX", country: "US", customsApproved: false },
  { name: "Albuquerque International Sunport", iataCode: "ABQ", cbpPortCode: "2401", city: "Albuquerque", state: "NM", country: "US", customsApproved: false },
  { name: "Tucson International Airport", iataCode: "TUS", cbpPortCode: "2601", city: "Tucson", state: "AZ", country: "US", customsApproved: true },
  { name: "Las Vegas Harry Reid International Airport", iataCode: "LAS", cbpPortCode: "2901", city: "Las Vegas", state: "NV", country: "US", customsApproved: true },
  { name: "Reno-Tahoe International Airport", iataCode: "RNO", cbpPortCode: "2901", city: "Reno", state: "NV", country: "US", customsApproved: false },
  { name: "Sacramento International Airport", iataCode: "SMF", cbpPortCode: "2801", city: "Sacramento", state: "CA", country: "US", customsApproved: true },
  { name: "Oakland International Airport", iataCode: "OAK", cbpPortCode: "2801", city: "Oakland", state: "CA", country: "US", customsApproved: false },
  { name: "San Jose International Airport", iataCode: "SJC", cbpPortCode: "2801", city: "San Jose", state: "CA", country: "US", customsApproved: false },
  { name: "Burbank Bob Hope Airport", iataCode: "BUR", cbpPortCode: "2801", city: "Burbank", state: "CA", country: "US", customsApproved: false },
  { name: "Long Beach Airport", iataCode: "LGB", cbpPortCode: "2801", city: "Long Beach", state: "CA", country: "US", customsApproved: false },
  { name: "Ontario International Airport", iataCode: "ONT", cbpPortCode: "2801", city: "Ontario", state: "CA", country: "US", customsApproved: false },
  { name: "Palm Springs International Airport", iataCode: "PSP", cbpPortCode: "2801", city: "Palm Springs", state: "CA", country: "US", customsApproved: false },
  { name: "Santa Barbara Airport", iataCode: "SBA", cbpPortCode: "2801", city: "Santa Barbara", state: "CA", country: "US", customsApproved: false },
  { name: "Monterey Regional Airport", iataCode: "MRY", cbpPortCode: "2801", city: "Monterey", state: "CA", country: "US", customsApproved: false },
  { name: "Fresno Yosemite International Airport", iataCode: "FAT", cbpPortCode: "2801", city: "Fresno", state: "CA", country: "US", customsApproved: false },
  { name: "Eugene Airport", iataCode: "EUG", cbpPortCode: "2902", city: "Eugene", state: "OR", country: "US", customsApproved: false },
  { name: "Spokane International Airport", iataCode: "GEG", cbpPortCode: "3004", city: "Spokane", state: "WA", country: "US", customsApproved: false },
  { name: "Bellingham International Airport", iataCode: "BLI", cbpPortCode: "3009", city: "Bellingham", state: "WA", country: "US", customsApproved: true },
  { name: "Boise Airport", iataCode: "BOI", cbpPortCode: "3101", city: "Boise", state: "ID", country: "US", customsApproved: false },
  { name: "Billings Logan International Airport", iataCode: "BIL", cbpPortCode: "3301", city: "Billings", state: "MT", country: "US", customsApproved: false },
  { name: "Missoula International Airport", iataCode: "MSO", cbpPortCode: "3302", city: "Missoula", state: "MT", country: "US", customsApproved: false },
  { name: "Casper/Natrona County International Airport", iataCode: "CPR", cbpPortCode: "3401", city: "Casper", state: "WY", country: "US", customsApproved: false },
  { name: "Jackson Hole Airport", iataCode: "JAC", cbpPortCode: "3401", city: "Jackson", state: "WY", country: "US", customsApproved: false },
  { name: "Sioux Falls Regional Airport", iataCode: "FSD", cbpPortCode: "3401", city: "Sioux Falls", state: "SD", country: "US", customsApproved: false },
  { name: "Rapid City Regional Airport", iataCode: "RAP", cbpPortCode: "3401", city: "Rapid City", state: "SD", country: "US", customsApproved: false },
  { name: "Fargo Hector International Airport", iataCode: "FAR", cbpPortCode: "3401", city: "Fargo", state: "ND", country: "US", customsApproved: false },
  { name: "Grand Forks International Airport", iataCode: "GFK", cbpPortCode: "3401", city: "Grand Forks", state: "ND", country: "US", customsApproved: false },
  { name: "Des Moines International Airport", iataCode: "DSM", cbpPortCode: "4201", city: "Des Moines", state: "IA", country: "US", customsApproved: false },
  { name: "Cedar Rapids Airport", iataCode: "CID", cbpPortCode: "4201", city: "Cedar Rapids", state: "IA", country: "US", customsApproved: false },
  { name: "Omaha Eppley Airfield", iataCode: "OMA", cbpPortCode: "4601", city: "Omaha", state: "NE", country: "US", customsApproved: false },
  { name: "Lincoln Airport", iataCode: "LNK", cbpPortCode: "4601", city: "Lincoln", state: "NE", country: "US", customsApproved: false },
  { name: "Wichita Eisenhower National Airport", iataCode: "ICT", cbpPortCode: "1901", city: "Wichita", state: "KS", country: "US", customsApproved: false },
  { name: "Tulsa International Airport", iataCode: "TUL", cbpPortCode: "4301", city: "Tulsa", state: "OK", country: "US", customsApproved: false },
  { name: "Will Rogers World Airport", iataCode: "OKC", cbpPortCode: "4301", city: "Oklahoma City", state: "OK", country: "US", customsApproved: false },
  { name: "Little Rock National Airport", iataCode: "LIT", cbpPortCode: "5701", city: "Little Rock", state: "AR", country: "US", customsApproved: false },
  { name: "Jackson-Medgar Wiley Evers International Airport", iataCode: "JAN", cbpPortCode: "2001", city: "Jackson", state: "MS", country: "US", customsApproved: false },
  { name: "Birmingham-Shuttlesworth International Airport", iataCode: "BHM", cbpPortCode: "0101", city: "Birmingham", state: "AL", country: "US", customsApproved: false },
  { name: "Huntsville International Airport", iataCode: "HSV", cbpPortCode: "0101", city: "Huntsville", state: "AL", country: "US", customsApproved: false },
  { name: "Mobile Regional Airport", iataCode: "MOB", cbpPortCode: "0101", city: "Mobile", state: "AL", country: "US", customsApproved: false },
  { name: "Columbia Metropolitan Airport", iataCode: "CAE", cbpPortCode: "4801", city: "Columbia", state: "SC", country: "US", customsApproved: false },
  { name: "Greenville-Spartanburg International Airport", iataCode: "GSP", cbpPortCode: "4801", city: "Greer", state: "SC", country: "US", customsApproved: false },
  { name: "Myrtle Beach International Airport", iataCode: "MYR", cbpPortCode: "4802", city: "Myrtle Beach", state: "SC", country: "US", customsApproved: false },
  { name: "Wilmington International Airport", iataCode: "ILM", cbpPortCode: "4803", city: "Wilmington", state: "NC", country: "US", customsApproved: false },
  { name: "Piedmont Triad International Airport", iataCode: "GSO", cbpPortCode: "4804", city: "Greensboro", state: "NC", country: "US", customsApproved: false },
  { name: "Norfolk International Airport", iataCode: "ORF", cbpPortCode: "1103", city: "Norfolk", state: "VA", country: "US", customsApproved: true },
  { name: "Lynchburg Regional Airport", iataCode: "LYH", cbpPortCode: "1103", city: "Lynchburg", state: "VA", country: "US", customsApproved: false },
  { name: "Roanoke-Blacksburg Regional Airport", iataCode: "ROA", cbpPortCode: "1103", city: "Roanoke", state: "VA", country: "US", customsApproved: false },
  { name: "Charleston International Airport", iataCode: "CHS", cbpPortCode: "4801", city: "Charleston", state: "SC", country: "US", customsApproved: true },
  { name: "Savannah/Hilton Head International Airport", iataCode: "SAV", cbpPortCode: "0101", city: "Savannah", state: "GA", country: "US", customsApproved: true },
  { name: "Augusta Regional Airport", iataCode: "AGS", cbpPortCode: "0101", city: "Augusta", state: "GA", country: "US", customsApproved: false },
  { name: "Macon Airport", iataCode: "MCN", cbpPortCode: "0101", city: "Macon", state: "GA", country: "US", customsApproved: false },
  { name: "Albany Southwest Georgia Regional Airport", iataCode: "ABY", cbpPortCode: "0101", city: "Albany", state: "GA", country: "US", customsApproved: false },
  { name: "Chattanooga Metropolitan Airport", iataCode: "CHA", cbpPortCode: "4801", city: "Chattanooga", state: "TN", country: "US", customsApproved: false },
  { name: "Knoxville McGhee Tyson Airport", iataCode: "TYS", cbpPortCode: "4801", city: "Knoxville", state: "TN", country: "US", customsApproved: false },
  { name: "Tri-Cities Regional Airport", iataCode: "TRI", cbpPortCode: "4801", city: "Blountville", state: "TN", country: "US", customsApproved: false },
  { name: "Lexington Blue Grass Airport", iataCode: "LEX", cbpPortCode: "1901", city: "Lexington", state: "KY", country: "US", customsApproved: false },
  { name: "Dayton International Airport", iataCode: "DAY", cbpPortCode: "4101", city: "Dayton", state: "OH", country: "US", customsApproved: false },
  { name: "Toledo Express Airport", iataCode: "TOL", cbpPortCode: "4101", city: "Toledo", state: "OH", country: "US", customsApproved: false },
  { name: "Akron-Canton Airport", iataCode: "CAK", cbpPortCode: "4101", city: "Green", state: "OH", country: "US", customsApproved: false },
  { name: "Erie International Airport", iataCode: "ERI", cbpPortCode: "4701", city: "Erie", state: "PA", country: "US", customsApproved: false },
  { name: "Harrisburg International Airport", iataCode: "MDT", cbpPortCode: "4701", city: "Middletown", state: "PA", country: "US", customsApproved: false },
  { name: "Allentown-Bethlehem-Easton International Airport", iataCode: "ABE", cbpPortCode: "4701", city: "Allentown", state: "PA", country: "US", customsApproved: false },
  { name: "Syracuse Hancock International Airport", iataCode: "SYR", cbpPortCode: "0901", city: "Syracuse", state: "NY", country: "US", customsApproved: false },
  { name: "Albany International Airport", iataCode: "ALB", cbpPortCode: "0901", city: "Albany", state: "NY", country: "US", customsApproved: false },
  { name: "Buffalo Niagara International Airport", iataCode: "BUF", cbpPortCode: "0901", city: "Buffalo", state: "NY", country: "US", customsApproved: true },
  { name: "Stewart International Airport", iataCode: "SWF", cbpPortCode: "4701", city: "Newburgh", state: "NY", country: "US", customsApproved: false },
  { name: "LaGuardia Airport", iataCode: "LGA", cbpPortCode: "4701", city: "New York", state: "NY", country: "US", customsApproved: false },
  { name: "Newark Liberty International Airport", iataCode: "EWR", cbpPortCode: "4501", city: "Newark", state: "NJ", country: "US", customsApproved: true },
  { name: "Atlantic City International Airport", iataCode: "ACY", cbpPortCode: "4501", city: "Atlantic City", state: "NJ", country: "US", customsApproved: false },
  { name: "Providence T.F. Green Airport", iataCode: "PVD", cbpPortCode: "0401", city: "Providence", state: "RI", country: "US", customsApproved: false },
  { name: "Hartford Bradley International Airport", iataCode: "BDL", cbpPortCode: "0401", city: "Windsor Locks", state: "CT", country: "US", customsApproved: false },
  { name: "Portland International Jetport", iataCode: "PWM", cbpPortCode: "0101", city: "Portland", state: "ME", country: "US", customsApproved: false },
  { name: "Burlington International Airport", iataCode: "BTV", cbpPortCode: "0101", city: "Burlington", state: "VT", country: "US", customsApproved: true },
  { name: "Manchester-Boston Regional Airport", iataCode: "MHT", cbpPortCode: "0401", city: "Manchester", state: "NH", country: "US", customsApproved: false },
  { name: "Bangor International Airport", iataCode: "BGR", cbpPortCode: "0101", city: "Bangor", state: "ME", country: "US", customsApproved: true },
  { name: "Hilo International Airport", iataCode: "ITO", cbpPortCode: "3101", city: "Hilo", state: "HI", country: "US", customsApproved: false },
  { name: "Kahului Airport", iataCode: "OGG", cbpPortCode: "3101", city: "Kahului", state: "HI", country: "US", customsApproved: false },
  { name: "San Juan Luis Munoz Marin International Airport", iataCode: "SJU", cbpPortCode: "4901", city: "San Juan", state: "PR", country: "US", customsApproved: true },
  { name: "Aguadilla Rafael Hernandez Airport", iataCode: "BQN", cbpPortCode: "4901", city: "Aguadilla", state: "PR", country: "US", customsApproved: true },
  { name: "Ponce Mercedita Airport", iataCode: "PSE", cbpPortCode: "4901", city: "Ponce", state: "PR", country: "US", customsApproved: false },
  { name: "St. Thomas Cyril E. King Airport", iataCode: "STT", cbpPortCode: "5001", city: "Charlotte Amalie", state: "VI", country: "US", customsApproved: true },
  { name: "St. Croix Henry E. Rohlsen Airport", iataCode: "STX", cbpPortCode: "5001", city: "Christiansted", state: "VI", country: "US", customsApproved: true },
  { name: "Guam International Airport", iataCode: "GUM", cbpPortCode: "5001", city: "Hagatna", state: "GU", country: "US", customsApproved: true },
  { name: "Saipan International Airport", iataCode: "SPN", cbpPortCode: "5001", city: "Saipan", state: "MP", country: "US", customsApproved: true },
  { name: "Laredo International Airport", iataCode: "LRD", cbpPortCode: "2304", city: "Laredo", state: "TX", country: "US", customsApproved: true },
  { name: "Brownsville South Padre Island International Airport", iataCode: "BRO", cbpPortCode: "2308", city: "Brownsville", state: "TX", country: "US", customsApproved: true },
  { name: "McAllen Miller International Airport", iataCode: "MFE", cbpPortCode: "2309", city: "McAllen", state: "TX", country: "US", customsApproved: true },
  { name: "Calexico International Airport", iataCode: "CXL", cbpPortCode: "2503", city: "Calexico", state: "CA", country: "US", customsApproved: true },
  { name: "Yuma International Airport", iataCode: "YUM", cbpPortCode: "2601", city: "Yuma", state: "AZ", country: "US", customsApproved: true },
  { name: "Douglas Bisbee International Airport", iataCode: "DUG", cbpPortCode: "2602", city: "Douglas", state: "AZ", country: "US", customsApproved: true },
  { name: "Grand Rapids Gerald R. Ford International Airport", iataCode: "GRR", cbpPortCode: "3801", city: "Grand Rapids", state: "MI", country: "US", customsApproved: false },
  { name: "Flint Bishop International Airport", iataCode: "FNT", cbpPortCode: "3801", city: "Flint", state: "MI", country: "US", customsApproved: false },
  { name: "Kalamazoo/Battle Creek International Airport", iataCode: "AZO", cbpPortCode: "3801", city: "Kalamazoo", state: "MI", country: "US", customsApproved: false },
  { name: "Lansing Capital City Airport", iataCode: "LAN", cbpPortCode: "3801", city: "Lansing", state: "MI", country: "US", customsApproved: false },
  { name: "Green Bay Austin Straubel International Airport", iataCode: "GRB", cbpPortCode: "3901", city: "Green Bay", state: "WI", country: "US", customsApproved: false },
  { name: "Madison Dane County Regional Airport", iataCode: "MSN", cbpPortCode: "3901", city: "Madison", state: "WI", country: "US", customsApproved: false },
  { name: "Milwaukee Mitchell International Airport", iataCode: "MKE", cbpPortCode: "3901", city: "Milwaukee", state: "WI", country: "US", customsApproved: true },
  { name: "Duluth International Airport", iataCode: "DLH", cbpPortCode: "3401", city: "Duluth", state: "MN", country: "US", customsApproved: false },
  { name: "Rochester International Airport", iataCode: "RST", cbpPortCode: "3401", city: "Rochester", state: "MN", country: "US", customsApproved: false },
  { name: "Colorado Springs Airport", iataCode: "COS", cbpPortCode: "5901", city: "Colorado Springs", state: "CO", country: "US", customsApproved: false },
  { name: "Grand Junction Regional Airport", iataCode: "GJT", cbpPortCode: "5901", city: "Grand Junction", state: "CO", country: "US", customsApproved: false },
  { name: "Aspen-Pitkin County Airport", iataCode: "ASE", cbpPortCode: "5901", city: "Aspen", state: "CO", country: "US", customsApproved: false },
  { name: "Vail Eagle County Regional Airport", iataCode: "EGE", cbpPortCode: "5901", city: "Eagle", state: "CO", country: "US", customsApproved: false },
  { name: "St. George Regional Airport", iataCode: "SGU", cbpPortCode: "2901", city: "St. George", state: "UT", country: "US", customsApproved: false },
  { name: "Provo Municipal Airport", iataCode: "PVU", cbpPortCode: "2901", city: "Provo", state: "UT", country: "US", customsApproved: false },
  { name: "El Paso International Airport", iataCode: "ELP", cbpPortCode: "2401", city: "El Paso", state: "TX", country: "US", customsApproved: true },
  { name: "Midland International Air & Space Port", iataCode: "MAF", cbpPortCode: "5503", city: "Midland", state: "TX", country: "US", customsApproved: false },
  { name: "Waco Regional Airport", iataCode: "ACT", cbpPortCode: "5501", city: "Waco", state: "TX", country: "US", customsApproved: false },
  { name: "Tyler Pounds Regional Airport", iataCode: "TYR", cbpPortCode: "5501", city: "Tyler", state: "TX", country: "US", customsApproved: false },
  { name: "Beaumont/Port Arthur Airport", iataCode: "BPT", cbpPortCode: "5301", city: "Beaumont", state: "TX", country: "US", customsApproved: false },
  { name: "Shreveport Regional Airport", iataCode: "SHV", cbpPortCode: "2001", city: "Shreveport", state: "LA", country: "US", customsApproved: false },
  { name: "Baton Rouge Metropolitan Airport", iataCode: "BTR", cbpPortCode: "2001", city: "Baton Rouge", state: "LA", country: "US", customsApproved: false },
  { name: "Lafayette Regional Airport", iataCode: "LFT", cbpPortCode: "2001", city: "Lafayette", state: "LA", country: "US", customsApproved: false },
  { name: "Gulfport-Biloxi International Airport", iataCode: "GPT", cbpPortCode: "2001", city: "Gulfport", state: "MS", country: "US", customsApproved: false },
  { name: "Charleston International Airport", iataCode: "CRW", cbpPortCode: "4801", city: "Charleston", state: "WV", country: "US", customsApproved: false },
  { name: "Huntington Tri-State Airport", iataCode: "HTS", cbpPortCode: "4801", city: "Huntington", state: "WV", country: "US", customsApproved: false },
  { name: "Morgantown Municipal Airport", iataCode: "MGW", cbpPortCode: "4801", city: "Morgantown", state: "WV", country: "US", customsApproved: false },
  { name: "Newport News/Williamsburg International Airport", iataCode: "PHF", cbpPortCode: "1103", city: "Newport News", state: "VA", country: "US", customsApproved: false },
  { name: "Hagerstown Regional Airport", iataCode: "HGR", cbpPortCode: "1301", city: "Hagerstown", state: "MD", country: "US", customsApproved: false },
  { name: "Salisbury Ocean City Regional Airport", iataCode: "SBY", cbpPortCode: "1301", city: "Salisbury", state: "MD", country: "US", customsApproved: false },
  { name: "Frederick Municipal Airport", iataCode: "FDK", cbpPortCode: "1301", city: "Frederick", state: "MD", country: "US", customsApproved: false },
  { name: "Wilmington Airport", iataCode: "ILG", cbpPortCode: "1401", city: "Wilmington", state: "DE", country: "US", customsApproved: false },
  { name: "Trenton-Mercer Airport", iataCode: "TTN", cbpPortCode: "4501", city: "Ewing Township", state: "NJ", country: "US", customsApproved: false },
  { name: "Cape Cod Gateway Airport", iataCode: "HYA", cbpPortCode: "0401", city: "Hyannis", state: "MA", country: "US", customsApproved: false },
  { name: "Barnstable Municipal Airport", iataCode: "HYA", cbpPortCode: "0401", city: "Barnstable", state: "MA", country: "US", customsApproved: false },
  { name: "Nantucket Memorial Airport", iataCode: "ACK", cbpPortCode: "0401", city: "Nantucket", state: "MA", country: "US", customsApproved: false },
  { name: "Martha's Vineyard Airport", iataCode: "MVY", cbpPortCode: "0401", city: "Vineyard Haven", state: "MA", country: "US", customsApproved: false },
  { name: "Worcester Regional Airport", iataCode: "ORH", cbpPortCode: "0401", city: "Worcester", state: "MA", country: "US", customsApproved: false },
];

export async function ingestAirports(
  db: any,
  rawImportsTable: any,
  airportsTable: any,
  source: string
): Promise<number> {
  let added = 0;

  for (const airport of US_AIRPORTS_DATA) {
    try {
      await db.insert(rawImportsTable).values({
        source,
        dataType: "airport",
        rawData: airport,
        flagged: false,
      }).onConflictDoNothing();

      const result = await db.insert(airportsTable).values({
        name: airport.name,
        iataCode: airport.iataCode,
        cbpPortCode: airport.cbpPortCode,
        city: airport.city,
        state: airport.state,
        country: airport.country,
        customsApproved: airport.customsApproved,
        source,
        status: "pending",
        flaggedForReview: false,
        lastUpdated: new Date(),
      }).onConflictDoNothing().returning();

      if (result.length > 0) added++;
    } catch {
      // Skip duplicates silently
    }
  }

  return added;
}
